### ISSUE TITLE
Another error message problem for forward_call

### ISSUE THREAD

**Issue by QinxiangCao** [PrincetonUniversity/VST#120]
Although VST has been working hard to provide good error messages, here is another one not yet done.

Take current master branch (commit f779c3b) as an example. Let's comment out line 120-220 in progs/verif_reverse.v. And run it to line 290. It would be good since the order of verifying different functions does not matter in VST. Now, if we change line 61 from
  POST [ tint ]
into
  POST [ tuint ]
Then, line 286 will fail. It should fail because the return type of _sum_spec is wrong. But the error message there is hard to understand.

**Comment by andrew-appel** [comment]
Fixed in the next commit.
