### ISSUE TITLE
Compcert x86_64 and VST are not compatible

### ISSUE THREAD

**Issue by ildyria** [PrincetonUniversity/VST#139]
When using CONFIGURE to force the CompCert repository and if CompCert has been compiled with the `x86_64 linux` option it generate the following error:

```sh
File "./sepcomp/mem_lemmas.v", line 786, characters 25-27:
Error: The reference v0 was not found in the current environment.

Makefile:391: recipe for target 'sepcomp/mem_lemmas.vo' failed
make: *** [sepcomp/mem_lemmas.vo] Error 1
```

When compiling with a `CONFIGURE` file to force the path to the current version of CompCert.

Note that this error is not raised if CompCert is compiled with the `x86_32 linux` option.

**Comment by andrew-appel** [comment]
I am not at all surprised that today's VST does not work in 64-bit mode.  Compatibility with 64-bit architectures is planned for a future release, perhaps not too far in the future.  I believe all the code in veric/*.v and much of the code in floyd/*.v will be portable to 64-bit without change.

**Comment by andrew-appel** [comment]
This was fixed in August 2018.  VST now works in 64-bit mode, although it has not been extensively tested in 64-bit mode.
