### ISSUE TITLE
better diagnosis needed when load or store fails

### ISSUE THREAD

**Issue by dnaumann** [PrincetonUniversity/VST#148]
For code like this
q[0] = s
the appropriate sep conjunct to make this work is
data_at_ Tsh (tarray tuint 1) p
but by mistake I used
data_at_ Tsh tuint p
and the diagnostic wasn't helpful.
An example is in the deepDB repo, memmgr/verif_malloc.v commit af6049e

**Comment by andrew-appel** [comment]
Ditto if by mistake the SEP conjuct was   memory_block ... p.

In these cases, the load/store tactic should diagnose that a SEP conjunct covers the appropriate address range, but is not a data_at (or is a data_at with the wrong type), and give a better error message.

**Comment by dnaumann** [comment]
Two minor oddities: the error message sometimes repeats the same suggestion twice, and there's a missing parenthesis just before the equals.  For example:

Tactic failure: Please use assert_PROP to prove an equality of the form
(Vptr pblk
   (Ptrofs.add (Ptrofs.add poff (Ptrofs.repr (s + j * (s + WORD))))
      (Ptrofs.mul (Ptrofs.repr 4) (Ptrofs.of_ints (Int.repr 1)))) =
 field_address ?t ?path ?a)
or if this does not hold, prove an equality of the form
(Vptr pblk
   (Ptrofs.add (Ptrofs.add poff (Ptrofs.repr (s + j * (s + WORD))))
      (Ptrofs.mul (Ptrofs.repr 4) (Ptrofs.of_ints (Int.repr 1)))) =
 field_address ?t ?path ?a).

**Comment by andrew-appel** [comment]
Here's another example, easy to reproduce.  In progs/verif_field_loadstore.v, in Lemma body_sub1, immediately after start_function, add the following line:
'  match goal with |- context [SEP(?X p)] => set (foo:=X) end.  '
Then notice how the 'forward' command suggests a hint that is not at all useful.  This hint-suggestion should only be made when it will let the load-with-hint actually succeed.

**Comment by andrew-appel** [comment]
Fixed, as best I can.
