### ISSUE TITLE
VST broken with Coq master

### ISSUE THREAD

**Issue by Zimmi48** [PrincetonUniversity/VST#153]
Hi,
VST is currently failing on VST with the following error:
```
File "./floyd/library.v", line 78, characters 3-472:
Error:
The term "(compspecs * type)%type" has type
 "Type@{max(Set,compcert.lib.Maps.71,compcert.cfrontend.Ctypes.24)}"
while it is expected to have type "Type@{VST.veric.SeparationLogic.231}"
(universe inconsistency).
```
It was fine 3 days ago.

**Comment by andrew-appel** [comment]
Is this related to Coq 8.7.2?
That is, this works fine in Coq 8.7.1 . . .

**Comment by Zimmi48** [comment]
Hum, no I wouldn't expect that.
If this is a regression in Coq, it would be between 8.7 and 8.8.

**Comment by andrew-appel** [comment]
It also works fine in Coq 8.7.2.   Perhaps it's failing only in the Coq trunk?

**Comment by ildyria** [comment]
That is weird, I just pulled from master and I didn't had any trouble compiling with coq 8.7.2.

**Comment by andrew-appel** [comment]
Here's a version of floyd/library.v that parameterizes compspecs in a different way; see if it works in 8.8.

Require Import VST.floyd.base2.
Require Import VST.floyd.sublist.
Require Import VST.floyd.client_lemmas.
Require Import VST.floyd.closed_lemmas.
Require Import VST.floyd.compare_lemmas.
Require Import VST.floyd.semax_tactics.
Require Import VST.floyd.forward.
Require Import VST.floyd.call_lemmas.
Require Import VST.floyd.forward_lemmas.
Require Import VST.floyd.for_lemmas.
Require Import VST.floyd.nested_pred_lemmas.
Require Import VST.floyd.nested_field_lemmas.
Require Import VST.floyd.efield_lemmas.
Require Import VST.floyd.mapsto_memory_block.
Require Import VST.floyd.aggregate_type.
Require VST.floyd.aggregate_pred. Import VST.floyd.aggregate_pred.aggregate_pred.
Require Import VST.floyd.reptype_lemmas.
Require Import VST.floyd.data_at_rec_lemmas.
Require Import VST.floyd.field_at.
Require Import VST.floyd.field_compat.
Require Import VST.floyd.stronger.
Require Import VST.floyd.loadstore_mapsto.
Require Import VST.floyd.loadstore_field_at.
Require Import VST.floyd.nested_loadstore.
Require Import VST.floyd.local2ptree_denote.
Require Import VST.floyd.local2ptree_eval.
Require Import VST.floyd.proj_reptype_lemmas.
Require Import VST.floyd.replace_refill_reptype_lemmas.
Require Import VST.floyd.sc_set_load_store.
(*Require Import VST.floyd.unfold_data_at.*)
Require Import VST.floyd.entailer.
Require Import VST.floyd.globals_lemmas.
Require Import VST.floyd.diagnosis.
Require Import VST.floyd.freezer.
Import ListNotations.
Import String.

Definition body_lemma_of_funspec  {Espec: OracleKind} (ef: external_function) (f: funspec) :=
  match f with mk_funspec sig _ A P Q _ _ =>
    semax_external (map fst (fst sig)) ef A P Q
  end.

Definition try_spec (prog: program) (name: string) (spec: funspec) : list (ident*funspec) :=
 match ext_link_prog' (prog_defs prog) name with
 | Some id => [(id,spec)]
 | None => nil
 end.
Arguments try_spec prog name spec / .

Definition exit_spec' :=
 WITH u: unit
 PRE [1%positive OF tint]
   PROP () LOCAL() SEP()
 POST [ tvoid ]
   PROP(False) LOCAL() SEP().

Definition exit_spec (prog: program) := try_spec prog "exit" exit_spec'.
Arguments exit_spec prog / .

Parameter body_exit:
 forall {Espec: OracleKind},
  body_lemma_of_funspec
    (EF_external "exit"
       {| sig_args := AST.Tint :: nil; sig_res := None; sig_cc := cc_default |})
   exit_spec'.

Parameter malloc_token : forall {cs: compspecs}, share -> type -> val -> mpred.
Parameter malloc_token_valid_pointer:
  forall {cs: compspecs} sh t p, malloc_token sh t p |-- valid_pointer p.
Hint Resolve malloc_token_valid_pointer : valid_pointer.
Parameter malloc_token_local_facts:
  forall {cs: compspecs} sh t p, malloc_token sh t p |-- !! malloc_compatible (sizeof t) p.
Hint Resolve malloc_token_local_facts : saturate_local.
Parameter malloc_token_precise:
  forall {cs: compspecs} sh t p, predicates_sl.precise (malloc_token sh t p).

Definition malloc_spec'  {cs: compspecs} :=
   WITH t:type
   PRE [ 1%positive OF tuint ]
       PROP (0 <= sizeof t <= Int.max_unsigned;
                complete_legal_cosu_type t = true;
                natural_aligned natural_alignment t = true)
       LOCAL (temp 1%positive (Vint (Int.repr (sizeof t))))
       SEP ()
    POST [ tptr tvoid ] EX p:_,
       PROP ()
       LOCAL (temp ret_temp p)
       SEP (if eq_dec p nullval then emp
            else (malloc_token Tsh t p * data_at_ Tsh t p)).

Definition malloc_spec  {cs: compspecs} (prog: program) :=
   try_spec prog "_malloc" malloc_spec'.
Arguments malloc_spec {cs} prog / .

Parameter body_malloc:
 forall {Espec: OracleKind} {cs: compspecs} ,
  body_lemma_of_funspec EF_malloc malloc_spec'.

Definition free_spec'  {cs: compspecs} :=
   WITH t: type, p:val
   PRE [ 1%positive OF tptr tvoid ]
       PROP ()
       LOCAL (temp 1%positive p)
       SEP (malloc_token Tsh t p; data_at_ Tsh t p)
    POST [ Tvoid ]
       PROP ()
       LOCAL ()
       SEP ().

Definition free_spec   {cs: compspecs} (prog: program) :=
   try_spec prog "_free" free_spec'.
Arguments free_spec  {cs} prog / .

Parameter body_free:
 forall {Espec: OracleKind} {cs: compspecs} ,
  body_lemma_of_funspec EF_free free_spec'.

Definition library_G  {cs: compspecs} prog :=
  exit_spec prog ++ malloc_spec prog ++ free_spec prog.

Ltac with_library prog G := 
 let x := constr:(library_G prog) in
 let x := eval hnf in x in 
 let x := eval simpl in x in
 let y := constr:(x++G) in
 let y := eval cbv beta iota delta [app] in y in 
 with_library' prog y.

Lemma semax_func_cons_malloc_aux:
  forall {cs: compspecs} (gx : genviron) (t :type) (ret : option val),
(EX p : val,
 PROP ( )
 LOCAL (temp ret_temp p)
 SEP (if eq_dec p nullval
      then emp
      else malloc_token Tsh t p * data_at_ Tsh t p))%assert
  (make_ext_rval gx ret) |-- !! is_pointer_or_null (force_val ret).
Proof.
 intros.
 rewrite exp_unfold. Intros p.
 rewrite <- insert_local.
 rewrite lower_andp.
 apply derives_extract_prop; intro. hnf in H. rewrite retval_ext_rval in H.
 subst p.
 if_tac. rewrite H; entailer!.
 renormalize. entailer!.
Qed.

**Comment by Zimmi48** [comment]
> That is weird, I just pulled from master and I didn't had any trouble compiling with coq 8.7.2.

We are extra careful not to commit dangerous changes that could break stuff between patch-level versions. So I would expect the failure to be only when compiling against Coq master.

> Here's a version of floyd/library.v that parameterizes compspecs in a different way; see if it works in 8.8.

Could you put this in a code block? Otherwise, comments are rendered as italic and the code cannot easily be copied.

**Comment by andrew-appel** [comment]
Instead of putting it in a code block, I have done this:
1. In the latest commit (115e814), floyd/library.v uses a simpler parameterization that probably does not trigger the universe bug in the Coq 8.8 master branch (can you confirm this?).
2. In that commit, there's a new file, floyd/bug_coq88dev.v, that demonstrates the bug (since it's derived directly from the old floyd/library.v).  I suggest that the Coq team ensures that their travis-ci makefile builds this file  ("make" might do it), so you can use this as a regression test.

This simpler parameterization (not triggering the bug) is what we want anyway in VST,
so this Coq bug is not high priority for us.

**Comment by Zimmi48** [comment]
Thanks!

**Comment by ejgallego** [comment]
Dear Andrew (@andrew-appel),

the build failure in Coq 8.8+alpha is unfortunately a regression (https://github.com/coq/coq/issues/6913) due to the removal of some parameterization capabilities that were deemed deprecated.

Unfortunately your latest commit doesn't solve the issue so we'd have to discuss what the best solution is.

**Comment by ejgallego** [comment]
Oh sorry, the build fails, but it fails with:
```
File "./floyd/bug_coq88dev.v", line 32, characters 3-472:
Error:
The term "(compspecs * type)%type" has type
 "Type@{max(Set,compcert.lib.Maps.71,compcert.cfrontend.Ctypes.24)}"
while it is expected to have type "Type@{VST.veric.SeparationLogic.231}"
(universe inconsistency).
```
I am not sure why my script is still building this file, but this is a problem as the Travis script is building this file too.

**Comment by SkySkimmer** [comment]
It gets built because it's in the makefile. I guess VST didn't want the 
issue to silently disappear.

Gaëtan Gilbert
