### ISSUE TITLE
better hint for missing spec

### ISSUE THREAD

**Issue by dnaumann** [PrincetonUniversity/VST#159]
Two suggestions re hints.

First, when symbolic execution was at a function call and I tried 'forward', I got a lengthy error message about Witness_Type.  Out of curiousity I tried 'hint'; the reply isn't helpful: 
Hint:  try 'autorewrite with norm'
Perhaps the tactic can detect that forward_call is needed?

Second: forward_call then failed with an unhelpful message, when it would have ideally said Gprog has no spec for this function.  The message:

Error:
In nested Ltac calls to "forward_call (constr)", "fwd_call", 
"fwd_call'", "prove_call_setup", "check_witness_type",
"check_witness_type" and "check_witness_type", last call failed.
Tactic failure: Type of witness does not match type required by funspec WITH clause.
Witness value: 
(n, bin) 
Witness type:  (Z * val)%type 
Funspec type: 
NOTE__Perhaps_you_need_to_Import_floyd_library___See_reference_manual_chapter___with_library.

**Comment by andrew-appel** [comment]
fixed.
