### ISSUE TITLE
tweak for nth_Znth in floyd/sublist

### ISSUE THREAD

**Issue by dnaumann** [PrincetonUniversity/VST#162]
Please remove the gratuitous argument (x:A) and perhaps reorder the args like this.
Lemma nth_Znth {A} {d: Inhabitant A}: 
   forall n (xs:list A), 0 <= n < Zlength xs -> (nth (Z.to_nat n) xs d) = (Znth n xs).

**Comment by andrew-appel** [comment]
Done.
