### ISSUE TITLE
Substitution in entailer! is dangerous if user has an evar in the proof goal.

### ISSUE THREAD

**Issue by QinxiangCao** [PrincetonUniversity/VST#186]
When instantiating an evar in Coq, it is very critical what assumptions can be used, i.e. what is in the scope.

In principle, any variables or assumptions that introduced after the evar was created should not be used. This is understandable. For example the following example should fail and does fail, or else it would have proved something unprovable.

Goal exists x: nat, forall y, x = y.
  eexists.
  intros.
  reflexivity. (* fail. Unable to unify "?x" with "y" (cannot instantiate "?x" because 
"y" is not in its scope). *)

In contrast, the variables that introduced before when the evar was created should be usable. Here is a more complicate example:

Goal forall y z: nat, z = y ->
  exists (x: {x | x = y}), proj1_sig x + y = proj1_sig x + z /\ exists H: z = y, x = exist _ _ H.
  intros.
  eexists.
  split.
  + (* branch 1 *)
    f_equal.
    subst; auto.
  + (* branch 2 *)
    refine (@ex_intro _ _ _ eq_refl).
    exact H.
Qed.

In branch 2, we instantiate x using y, z and H, which are all introduced before the "eexists" commands. However, if we prove branch 1 using "rewrite" or "subst" or "clear" when the evar is still in the coq context, then branch 2 will fail. The following is a long list of possible implementations of branch 1. Some succeed and some fail.

    (* branch 1; fail - H disappear *)
    subst.
    reflexivity.
    (* branch 1; fail - Qed fail *)
    rewrite H.
    reflexivity.
    (* branch 1; fail - Qed fail *)
    rewrite <- H.
    reflexivity.
    (* branch 1; fail - H disappear *)
    rewrite H.
    clear H.
    reflexivity.
    (* branch 1; succeed *)
    f_equal.
    exact H.
    (* branch 1; succeed *)
    f_equal.
    rewrite H.
    clear H.
    reflexivity.
    (* branch 1; fail - H disappear *)
    apply f_equal2_plus.
    - clear H; reflexivity.
    - auto.
    (* branch 1; succeed *)
    apply f_equal2_plus.
    - reflexivity.
    - auto.

In VST, if there is a user-introduced evar, then the forward tactic will, at some point, split the proof goal into two (or more), one is a typechecking requirement and the other is the leftover for user's later forward verification. Now, if the first goal's solver uses rewrite, subst, or clear, then the problem illustrated above will happen.

A potential solution is: either (1) prohibit subst in entailer, (2) choose not to do subst in entailer if an evar is found, or (3) give user a warning when a evar is found.

**Comment by andrew-appel** [comment]
I've implemented option (2).  safe_subst, called by go_lower (and entailer) fails if there is a relevant evar.
