### ISSUE TITLE
"fail 99" in advise_forward_call breaks "try forward", "repeat forward", etc.

### ISSUE THREAD

**Issue by ANogin** [PrincetonUniversity/VST#187]
In some places we have a sequence of 0 or more "easy" steps (like variable assignments) followed by a function call. With the number of the "easy" steps not always uniform (or at times changing slightly as the code synthesis is tweaked), we would at times use `try forward; forward_call ...` and `repeat forward; forward_call ...`. The recent change (6a2dc0ee023294aa5d1718d9d4734a05a0e805c2) adding "fail 99" hint to advise_forward_call means the hint "error" pops outside of try/repeat. 

If this is intentional and/or hard to avoid, then not a big deal - would not be hard for us to tweak the tactics/proofs, but if this is unintentional, then perhaps the hint could be implemented less invasively?

https://github.com/PrincetonUniversity/VST/blob/f412a84c0c8070998b99c8ce6ec25c08a72d7339/floyd/forward.v#L2836

**Comment by andrew-appel** [comment]
Fixed in latest commit.
