### ISSUE TITLE
VST.veric.lift `_ notation conflicts with the one from Program.Util

### ISSUE THREAD

**Issue by ANogin** [PrincetonUniversity/VST#195]
Not sure whether this is something worth doing anything about, but thought it may be helpful to point out.

The conflicting notations are:

coq/theories/Program/Utils.v:
  ``Notation " `  t " := (proj1_sig t) (at level 10, t at next level) : program_scope.``

VST/veric/lift.v:
  ``Notation "'`' x" := (liftx x) (at level 9).``

I noticed this when trying to use the [Coq-Equations](https://github.com/mattam82/Coq-Equations) plugin: 
```
Require Import floyd.proofauto.
From Equations Require Import Equations.
```
results in ``Notation ` _ is already defined at level 9 with arguments at next level while it is now required to be at level 10 with arguments at next level.`` error.

**Comment by andrew-appel** [comment]
It might be possible to put our backquote notation at level 10 instead of 9.  Then we would still have two different notations that you can't use at the same time, but at least you can have them in the same proof development.

**Comment by ANogin** [comment]
Yes, that would be helpful.

**Comment by andrew-appel** [comment]
Fixed in most recent commit.
