### ISSUE TITLE
entailer not applying memory_block_valid_pointer

### ISSUE THREAD

**Issue by dnaumann** [PrincetonUniversity/VST#201]
entailer! failed to prove an entailment that proved by the following steps.     
   apply denote_tc_test_eq_split; auto with valid_pointer.
   apply memory_block_valid_ptr; auto. rep_omega.

Example in verif_malloc.v  commit (search for "ISSUE" or run til it breaks)
0c5d96a2049c777c32ca8bc18b64abb93e4717c4

**Comment by andrew-appel** [comment]
Fixed in latest commit.
