### ISSUE TITLE
Fold id names

### ISSUE THREAD

**Issue by jldodds** [PrincetonUniversity/VST#21]
When we reflect, identifier names e.g. `_p` will be unfolded into positives. Here are a couple of solutions 
1.  create ptree in `start_function` mapping positives to "folded positives", supply this to the denotation function
2. create list of pairs in `start_function`  tactic with the same mapping. Use `change` in ltac to replace the unfolded values

**Comment by andrew-appel** [comment]
In the current VST-Floyd's approach to smaller-scale reflect, this is not really an issue.
