### ISSUE TITLE
Last commit broke VST compilation at least with Coq v8.8 and master

### ISSUE THREAD

**Issue by Zimmi48** [PrincetonUniversity/VST#211]
Commit e200895fab02fdc6e4785f47040f23d5ace6306c broke the compilation of VST with Coq `v8.8` and `master` branches. I can't check if it still compiles with Coq 8.7 at the present time

I can guarantee that this commit is the offending commit because I have several builds using the previous commit which succeeded and several builds using this commit which failed in the same way.

The error message is:
```
File "./veric/SequentialClight.v", line 59, characters 22-23:
Error: This proof is focused, but cannot be unfocused this way
```

https://github.com/PrincetonUniversity/VST/blob/e200895fab02fdc6e4785f47040f23d5ace6306c/veric/SequentialClight.v#L59

Apparently, the automation here has become weaker.

**Comment by mansky1** [comment]
This is definitely my fault, but it raised no errors on our Travis and it compiles on my machine. I'll investigate further.

**Comment by lennartberinger** [comment]
Yes, it's also broken in 8.7.2 - but the last VST commit to this file was 
23 days ago. I'm not very familiar with this file - maybe the issue is 
related to recent work on ghost state?

L.

----- Original Message -----

**Comment by mansky1** [comment]
Okay, the newest commit should fix it. That file hadn't made it into our Travis target. It's in now, so this shouldn't happen again.

**Comment by ejgallego** [comment]
Dear @Zimmi48 and @mansky1 thank you for taking care of this issue.

Note that since a couple of days, and thanks to much increased CI capacity generously donated by Gitlab, Coq CI tests the whole of VST, that is to say, `make`. So indeed, it seems that Coq's CI is testing a strictly larger subset of VST than VST's own Travis.

**Comment by Zimmi48** [comment]
Thanks for the quick reaction everyone!
