### ISSUE TITLE
rep_omega fail with Ptrofs.max_unsigned in context

### ISSUE THREAD

**Issue by LukeXuan** [PrincetonUniversity/VST#212]
Consider the following lemma,

``` coq
Lemma demonstrate: forall a, 0 <= a <= 0 -> 0 <= a <= Ptrofs.max_unsigned.
```

This should be solvable by the `rep_omega` tactic but it fails.

After some investigation it seems like the `eval compute Ptrofs.max_unsigned` used in `rep_omega` failing to reduce the term into a concrete term caused the problem.

**Comment by andrew-appel** [comment]
Fixed in latest commit.

**Comment by andrew-appel** [comment]
Really fixed now.
