### ISSUE TITLE
entailer! does not derive valid_pointer from data_at

### ISSUE THREAD

**Issue by LukeXuan** [PrincetonUniversity/VST#217]
Consider the following example,

```coq
Lemma test: forall n p,
    0 < n ->
    data_at_ Tsh (tarray tint n) p |-- valid_pointer p.
```
It should be solvable by the `valid_pointer` database through `data_at_valid_ptr` lemma and should be solved by `entailer!`. Actually, this is a part of the solver for `denote_tc_test_eq` goals. However, `entailer!` fails at it.

**Comment by LukeXuan** [comment]
There are two problem here:

1. the `valid_pointer` database's pattern matching actually does not match the `data_at_` goal.

2. even if it's `data_at`, the tactic used in the second branch is `reflexivity`, which should actually not be used upon a goal of form `_ < _`.

**Comment by andrew-appel** [comment]
Fixed in next commit.

**Comment by LukeXuan** [comment]
If the type is an array, then `sizeof` will be evaluated to a form `_ * Z.max 0 _`, which rep_omega cannot handle itself.

However, the form we want to prove is `sizeof _ > 0`, it force us to establish the right hand side is greater than `0`. So my suggestion is to try `rewrite Z.max_r by rep_omega` for the subgoal first.

**Comment by andrew-appel** [comment]
if the size of the array is a constant `n`, then `Z.max 0 n` is no problem, even without `Z.max_r`.   Is your situation that `n` is a variable, but `rep_omega` can prove `n>0` ?

**Comment by LukeXuan** [comment]
Yes. I'm proving things like a cstring but without a tailing `\0`, but I know its length is greater than 0(ensured through preconditions, etc.).
