### ISSUE TITLE
entailer(!) is sometimes slow or does not terminate.

### ISSUE THREAD

**Issue by ildyria** [PrincetonUniversity/VST#224]
There are goals where this takes forever:
```
entailer!.
```

but where this solves it in seconds
```
(* prevent computations... *)
remember (M a a) as m.
(* prevent the substitution in entailer! *)
clear Heqm.
entailer!.
```

This is due to the fact that `entailer(!)` tend to *extract/subst/unfold/compute* more than it needs to.
Would it be possible to have a *simpler/lighter* version of `entailer` ?

**Comment by andrew-appel** [comment]
Several things have been done to address this issue, but there is no perfect answer.
