### ISSUE TITLE
progs/verif_evenodd_spec.v works but in an unexpected way

### ISSUE THREAD

**Issue by LukeXuan** [PrincetonUniversity/VST#227]
`progs/verif_evenodd_spec.v`, while it can actually compile, I found that it's relying on the coincidence of the two functions taking the same name for its parameters.

`clightgen` only define the parameters of functions that is defined in a single c file(even multiple c files is included in the command line), but those with only declaration are not.

As a result, if I change the function signature into `int odd(unsigned int odd_n);` and `int even(unsigned int even_n);`, the declaration of funspec won't pass, as it now reports `_odd_n` is not defined.

**Comment by andrew-appel** [comment]
This issue has been resolved: we no longer rely on parameter names in funspecs.
