### ISSUE TITLE
Assignment to typedef pointers cannot type check

### ISSUE THREAD

**Issue by LukeXuan** [PrincetonUniversity/VST#230]
Consider the following C program,

```c
#include <stdlib.h>

struct a {
  int b;
};

typedef struct a *c;

void foo() {
  c d = NULL;
}

```

with whatever spec that works for the function, after `start_function` and `forward`, we are reported that `Type_of_right_hand_side_does_not_match_type_of_assigned_variable`, however it should type check.

**Comment by andrew-appel** [comment]
This seems to be fixed now.
