### ISSUE TITLE
drop precision and valid_pointer from malloc_token

### ISSUE THREAD

**Issue by dnaumann** [PrincetonUniversity/VST#231]
malloc_token in floyd/library currently specifies two requirements that are untenable for the implementation in DeepSpecDB/memmgr and probably other sensible implementations.
- Parameter malloc_token_valid_pointer makes malloc_token p inconsistent with the other postcondition of malloc, namely data_at_ Tsh p.  A possible solution would be for the memory manager to retain a share of the allocated block; perhaps that can be motivated in terms of ensuring that free must be called, but it would be simpler to just drop the requirement.
- Parameter malloc_token_precise is unsatisfiable if the malloc_token is used to account for chunks that are wasted for purposes of alignment, because uninitialized memory_block or data_at_ is not precise.

**Comment by andrew-appel** [comment]
Pull request #288 addresses this issue as described above.
