### ISSUE TITLE
go_lower fail when there is local predicate on variables not in the environment

### ISSUE THREAD

**Issue by LukeXuan** [PrincetonUniversity/VST#232]
consider the function from [here](https://github.com/PrincetonUniversity/DeepSpecDB/blob/bordernode-refactor/src/verifiable.c#L139).

```c
const void *BN_ExportSuffixValue(BorderNode_T bn, KVKey_T *key) {
  if (bn->keySuffix != NULL) {
    *key = KV_MoveKey(bn->keySuffix, bn->keySuffixLength);
    bn->keySuffix = NULL;
    bn->keySuffixLength = 0;
  }
  else {
    *key = NULL;
  }

  const void *ret_temp = bn->suffixLink;
  bn->suffixLink = NULL;
  return ret_temp;
}
```

when proving it, I made an mistake by copy-pasting the join postcondition from goal window and introduced a local predicate on a temporary variable in the branch of the if statement.
```coq
forward_if (EX k': val * val,
        PROP ()
        LOCAL (temp _t'1 _; temp _bn p; temp _key k)
        SEP (key_rep Tsh s (fst k') (snd k'); malloc_token Tsh tkey (fst k');
             malloc_token sh_bordernode tbordernode p;
             field_at sh_bordernode tbordernode [StructField _prefixLinks] l p;
             field_at sh_bordernode tbordernode [StructField _suffixLink] v p;
             field_at sh_bordernode tbordernode [StructField _keySuffix] (Vint (Int.repr 0)) p;
             field_at sh_bordernode tbordernode [StructField _keySuffixLength] (Vint (Int.repr 0)) p;
             data_at sh_keybox tkeybox (fst k') k)
      )%assert
```

The following statement of pointer assignment requires an type checking and calls `entailer!` to solve it will lead to error message of "The entailer tactic works only on entailments _ |-- _". Some investigation indicates that this is caused by failure in `go_lower` when trying to check the type for the non-existing local variable, but I failed to reproduce the problem in any simpler code.

**Comment by andrew-appel** [comment]
Fixed.
