### ISSUE TITLE
VST is getting slower and slower. :(

### ISSUE THREAD

**Issue by ildyria** [PrincetonUniversity/VST#238]
While it gets "smarter" it is frustrating to see proof that used to compile that does not terminate anymore.
One of the reason is that tactics provided tries to solve more than the user sometimes want.

Some functions or variables are unnecessarily expanded, leading to goal too big to be usable and infinite loop. I am now forced to dig the lemmas I need into the core of VST instead of using the tactics...

Because `forward_if` does not terminate, I have to replace `forward_if cond` with:
```
apply semax_seq with cond.
match goal with
| |- semax ?Delta (PROPx ?P (LOCALx ?Q (SEPx ?R))) (Sifthenelse ?e ?c1 ?c2) _ =>
   let HRE := fresh "H" in let v := fresh "v" in
    evar (v: val);
    do_compute_expr Delta P Q R e v HRE;
    simpl in v;
    apply (semax_ifthenelse_PQR' _ v)
end.
```
and then solve the generated goals manually (which in the end will be faster than using `forward_if`.

It often happens for other tactics such as `forward` when a `return` is involved, eg a `forward` should be able to do the following but doing it by hand is way faster:
```
all: unfold abbreviate.
all: eapply (semax_return_None _ _ _ _ _ (stackframe_of f_S) []).
all: try reflexivity.
all: try apply return_outer_gen_refl.
all: try apply return_inner_gen_canon_nil.
all: try (eapply canonicalize_stackframe ; [ reflexivity| ]).
all: try apply Forall2_nil.
all: match goal with | [ |- context[[?A] ++ []] ] => change ([A] ++ []) with ([A]) end.
all: unfold_nm_overlap_array_sep.
```

I do appreciate the efforts of the VST team to improve their tool and make it more powerful but in this case the result is unfortunately counter productive.

**Comment by ildyria** [comment]
It seems that the following block of code speed up my proofs:

```coq
(* Save current normalize *)
Ltac normalize_VST :=  try match goal with |- context[subst] =>  autorewrite with subst typeclass_instances end;
 try match goal with |- context[ret_assert] =>  autorewrite with ret_assert typeclass_instances end;
 match goal with
 | |- semax _ _ _ _ =>
  floyd.seplog_tactics.normalize;
  repeat
  (first [ simpl_tc_expr
         | simple apply semax_extract_PROP; fancy_intros true
         | move_from_SEP
         ]; cbv beta; msl.log_normalize.normalize)
  | |- _  =>
    floyd.seplog_tactics.normalize
  end.

(* idtac the current one: hope for speed. *)
Ltac normalize ::= idtac.
(* This is way way too agressive. *)
Ltac safe_subst_any ::= idtac.
```

**Comment by andrew-appel** [comment]
These problems have been largely addressed:
- entailer(!) no longer does `simpl`, which prevents many blowups
- reliance on `normalize` is reduced
- `safe_subst_any` has been restricted, so it doesn't rewrite in the presence of unification variables
