### ISSUE TITLE
forward generate a non terminating QED

### ISSUE THREAD

**Issue by ildyria** [PrincetonUniversity/VST#248]
My proof terminates and is Guarded (as per Fabian advice)
![2018-06-29_1920x1080_15 04 03](https://user-images.githubusercontent.com/627094/42095191-359e06e0-7bb2-11e8-890d-b334ab078858.png)

It is difficult to provide a Minimum Working Example in this case, so I will try to give a view via screenshots.

Here is the situation.
![2018-06-29_1920x1080_15 35 04](https://user-images.githubusercontent.com/627094/42095193-35d75fbc-7bb2-11e8-9516-04ca1309de4e.png)
We can step through it and *close* it with `destruct` of `False` and `Qed` it:
![2018-06-29_1920x1080_15 31 25](https://user-images.githubusercontent.com/627094/42095192-35bd2e58-7bb2-11e8-8388-bf2e11c61e83.png)

If we don't *close* the goal, then we step through the `forward`:

![2018-06-29_1920x1080_15 35 25](https://user-images.githubusercontent.com/627094/42095194-35f0c218-7bb2-11e8-8c9f-f1b207772e46.png)

And if we *close* then the goal after the `forward` (not even in an entailment situation). This leads to the infinite loop in `Qed.`
![2018-06-29_1920x1080_15 45 46](https://user-images.githubusercontent.com/627094/42095658-84198758-7bb3-11e8-9968-be144b44deba.png)

**Comment by andrew-appel** [comment]
I can't really understand this issue report enough to diagnose the problem.  I will close this issue, but if you can explain more, feel free to reopen it.
