### ISSUE TITLE
forward_call: unhelpful error message

### ISSUE THREAD

**Issue by akravc** [PrincetonUniversity/VST#259]
When a function call is using a variable which doesn't have a specified value in the LOCAL clause, forward_call results in an unhelpful error message. 

Message: Actual_parameters_cannot_be_coerced_to_formal_parameter_types
![screen shot 2018-07-11 at 9 49 51 am](https://user-images.githubusercontent.com/5713264/42576217-dfb4dcc6-84ef-11e8-9889-9b26bf3024bb.png)

**Comment by andrew-appel** [comment]
This seems to have been fixed sometime in the last two months.  The error message is now much better.
