### ISSUE TITLE
Clarify what structured-data predicates to use in ref manual

### ISSUE THREAD

**Issue by jldodds** [PrincetonUniversity/VST#26]
It would be great if the refcard gave more information about when to use each of the 3 structured-data predicates.

My current understanding is
- **array_at** use only when you need to join-split arrays, for example a program like mergesort on arrays
- **field_at** use when you want to load or store from the middle of a data-structure
- **data_at** use if you are only going to load or store from the top level of the data-structure

Can you use `field_at` whenever you would use `data_at` but at a slight cost of convenience?

**Comment by andrew-appel** [comment]
The reference manual now has adequate descriptions of this stuff.
