### ISSUE TITLE
VST CI broken

### ISSUE THREAD

**Issue by ejgallego** [PrincetonUniversity/VST#261]
Dear VST devs,

it seems that
https://github.com/PrincetonUniversity/VST/commit/70233fdbb676eacd23e14b24dabc8f7ef1e00004

forgot to commit some files and both VST and Coq's CI are broken by this change.

Best regards,
Emilio

**Comment by mansky1** [comment]
You're quite right, and I apologize. I meant to avoid committing the changes to the Makefile. I believe it's fixed now, but I'm waiting for the Travis results.

**Comment by mansky1** [comment]
Fixed. I'll be more careful in the future.

**Comment by ejgallego** [comment]
Thanks!
