### ISSUE TITLE
forward_for_simple_bound generates incorrect premise/goal for negative initial value of loop variable

### ISSUE THREAD

**Issue by txyyss** [PrincetonUniversity/VST#262]
I have the following simple program:

> unsigned sumarray(unsigned a[], int n) {
  int i; unsigned s;
  s=0;
  for (i=-1; i< n - 1; i++)
    s += a[i + 1];
  return s;
}

When I try to use the forward_for_simple_bound tactic, it seems that this tactic can not generate the correct premise and proof goal. I wrote more details as comments in verif_loop_minus1.v:

[verif_loop_minus1.v.txt](https://github.com/PrincetonUniversity/VST/files/2203045/verif_loop_minus1.v.txt)
[loop_minus1.v.txt](https://github.com/PrincetonUniversity/VST/files/2203046/loop_minus1.v.txt)
[loop_minus1.c.txt](https://github.com/PrincetonUniversity/VST/files/2203047/loop_minus1.c.txt)

I put these files in VST/progs/ to illustrate the possible problem.

**Comment by QinxiangCao** [comment]
The reason of this problem is because of how "-1" is interpreted in Clight.

It is (Eunop Oneg (Econst_int (Int.repr 1) tint) tint) and it is not (Econst_int (Int.repr (-1)) tint).

**Comment by QinxiangCao** [comment]
Now, this issue is solved. But, Shengyi, I did not see you adding these files to progs. Can you add them and prove it using my improved forward_for_simple_bound?
