### ISSUE TITLE
Make reified load also work with top level, dynamically sized arrays 

### ISSUE THREAD

**Issue by jldodds** [PrincetonUniversity/VST#27]
Currently reified symbolic execution (possibly incorrectly) guesses that the type of the relevant data_at is going to be the same as the type of the expression. This is correct unless the load is from a pointer to an array, in which case the type of the data_at will be different.

For now this will result in an unsolvable entailment. The solution is to do a mini-cancellation (on the pointer of the data_at) by checking equality with the pointers of all data_at in the precondition. The type of the data_at can then be supplied to the lemma application.

Reifying the c type and just letting cancellation deal with it is not a valid solution to this problem, because there is another variable that is dependent on the c type. Because of this, the lemma must be parameterized over the c type.

**Comment by QinxiangCao** [comment]
It is solved after we got a nth-solver.
