### ISSUE TITLE
VST does not build with Coq master (fcf is outdated)

### ISSUE THREAD

**Issue by JasonGross** [PrincetonUniversity/VST#282]
The `sha`/`hmac` targets (tested on this repo but not Coq's CI) depend on the bundled version of fcf.  This version no longer builds with Coq master because nested proofs are not allowed without `Set Nested Proofs Allowed`.  There was a PR on fcf merged a year ago which fixes this: https://github.com/adampetcher/fcf/pull/16.  Please update the bundled version of fcf.

**Comment by andrew-appel** [comment]
Fixed now.
