### ISSUE TITLE
entailer! does not derive denote_tc_test_eq from data_at_, but does from memory_block

### ISSUE THREAD

**Issue by dnaumann** [PrincetonUniversity/VST#298]
entailer! doesn't solve things like this:

  mm_inv gv * malloc_token Tsh t p * data_at_ Tsh t p
    |-- denote_tc_test_eq p (Vint (Int.repr 0))

but it does solve the variant with memory_block Tsh (sizeof t) p .

An easy workaround is to use sep_apply data_at__memory_block.

**Comment by andrew-appel** [comment]
Fixed in commit 23a85eab51a93c7a2ce7552b1f7975e9a934d7d8.
