### ISSUE TITLE
entailer slow with sizeof

### ISSUE THREAD

**Issue by dnaumann** [PrincetonUniversity/VST#299]
I encountered both entailer(!) and rep_omega very slow on goals involving sizeof.
For example, this works fast:
set (n:=sizeof t).
assert_PROP ( 0 <= n <= Ptrofs.max_unsigned - WORD ) by entailer!. 
But with n inlined it's very slow.
This example is in body_free in verif_malloc.v,  commit  b11d0eb3faa5435f66657c5 of DeepSpecDB.

Not a problem, the workaround is easy, I'm just puzzled.

**Comment by andrew-appel** [comment]
What's happening is that go_lower (called from entailer!) is calling "simpl", which changes the implicit argument (that you don't see) of (sizeof t).  This makes the (sizeof t) below the line beta-eta-equal to the (sizeof t) above the line, but only by a VERY slow equality test (built in to Coq).

The solution is to make go_lower avoid doing simpl.  Until last week, go_lower did simpl on the entire entailment; last week's commit changes it to avoid simpl on the left side of the entailment; my next commit (that I'm working on now) will avoid simpl on the right side of the entailment as well.

**Comment by andrew-appel** [comment]
This is resolved by commit 4a020835a1561e2d4beac51231b4af4027299209.
