### ISSUE TITLE
gather_SEP behaves unexpectedly in some situations

### ISSUE THREAD

**Issue by anshumanmohan** [PrincetonUniversity/VST#320]
The new gather_SEP accepts  patterns instead of index numbers. However, this seems to have some unexpected behaviour. 

For example, if the SEP is: 
SEP (data_at sh tint Vzero a; 
          data_at sh tint Vzero b; 
          data_at sh tint Vzero c; 
          data_at sh tint Vzero d)) 

and I run:
  gather_SEP (data_at _ _ _ a) (data_at _ _ _ d) (data_at _ _ _ b) 

I get: 
SEP (data_at sh tint Vzero a * (emp * data_at sh tint Vzero b);
     data_at sh tint Vzero c; data_at sh tint Vzero d)) 

However, I expected behaviour that was equivalent to "gather_SEP 0 3 1", i.e.: 
SEP (data_at sh tint Vzero a *
          (data_at sh tint Vzero d * data_at sh tint Vzero b);
     data_at sh tint Vzero c))

I've placed my files [here](https://github.com/anshumanmohan/gather_SEP_issue) so that you can recreate my minimal experiment.

**Comment by andrew-appel** [comment]
Fixed.
