### ISSUE TITLE
Coq 8.9.0 makes it hard to work with low-level assertions

### ISSUE THREAD

**Issue by mansky1** [PrincetonUniversity/VST#323]
One of the new features of 8.9 is:

The `simple apply` tactic now respects the `Opaque` flag when called from Ltac (`auto` still does not respect it).

Currently, the definition of `mpred` is `Opaque`, and `saturate_local` uses `simple eapply`. This causes `entailer` to break when working with the basic definitions from res_predicates, since they're defined as being of type `pred rmap` rather than `mpred`. Here's a simple example:

```
Require Import VST.floyd.proofauto.

Lemma test: forall sh t v p, readable_share sh -> mapsto sh t p v |-- !!(tc_val t v).
Proof.
  intros.
  unfold mapsto.
  destruct (access_mode t); try solve [entailer!].
  destruct (type_is_volatile t); try solve [entailer!].
  destruct p; try solve [entailer!].
  rewrite if_true by auto.
  Fail entailer!.
Abort.
```

**Comment by andrew-appel** [comment]
Sorry, my commit message for https://github.com/PrincetonUniversity/VST/commit/bd88be9f28bc4a55f6f81ee87c955839afa1e2f7 referred to issue #323 when I mean to refer to #329.
