### ISSUE TITLE
Update to latest Flocq/CompCert?

### ISSUE THREAD

**Issue by vbgl** [PrincetonUniversity/VST#325]
Recently (see https://github.com/AbsInt/CompCert/pull/283), CompCert has been updated to Flocq 3.1. Are there any plans to update the copy of CompCert that is embedded in VST to reflect these changes?

This question is motivated by the following changes to Coq: <https://github.com/coq/coq/pull/8638>. The development version of Coq will no longer be compatible with older versions of Flocq and CompCert.

Thanks.

**Comment by andrew-appel** [comment]
Last week I updated the master branch of VST to CompCert 3.5.   Does that include Flocq 3.1?

**Comment by vbgl** [comment]
Unfortunately no, it does not.

**Comment by andrew-appel** [comment]
Commit https://github.com/PrincetonUniversity/VST/commit/7e05a28011e1ae8e68e5ae873c55b4ca0ee98fc7 resolves this issue.

**Comment by vbgl** [comment]
Thank you very much!
