### ISSUE TITLE
Coq 8.9.0 alters the behavior of some VST tactics

### ISSUE THREAD

**Issue by anshumanmohan** [PrincetonUniversity/VST#329]
(Possibly a cousin once removed of #323)
The CertiGC team has found that a few (likely related) VST tactics behave unexpectedly when compiled using Coq 8.9.0, but work as before using earlier versions of Coq. We have spent some time trying to fix these on our end, but we're stuck. We've also failed to create MWEs to illustrate our point, so below we link to a recent version of our codebase. Does VST spot a pattern that we're missing? Any advice for us as we try to rework our code? 

Our code is [here](https://github.com/johndoe20190406/RamifyCoq). To recreate our problem, you will need to ignore steps 1.1 and 2.1 in our Readme, and just build with Coq 8.9.0. The files that break, annotated with the tactics that behave unexpectedly, are:
* sample_mark/verif_mark_bi.v: forward_if
* sample_mark/verif_unionfind.v: forward_call
* sample_mark/verif_unionfind_slim.v: forward_call
* sample_mark/verif_unionfind_rank.v: forward_call
* sample_mark/verif_unionfind_iter.v: entailer! and localize
* sample_mark/verif_unionfind_iter_rank.v: entailer! and localize

The last two files use entailer! in a straightforward lemma each, and we are actually able to get past the changed behavior of entailer and prove those lemmas ourselves. In both those files, however, we get into trouble at localize soon thereafter. If you'd like to see the problem, please just admit the lemmas that get into trouble with entailer ("graph_local_facts" in both files) and step ahead to the first use of localize.

**Comment by andrew-appel** [comment]
This is improved, perhaps entirely fixed, in commit https://github.com/PrincetonUniversity/VST/commit/bd88be9f28bc4a55f6f81ee87c955839afa1e2f7.

**Comment by anshumanmohan** [comment]
Hello, I'm afraid the move from `simple apply` to `apply` didn't work exactly as expected. Here is a little update from my end:

`verif_mark_bi.v`
	`forward_if` now goes through, but has funny new behavior. Of the four branches created by `forward_if`, only the first goes through without my changing the code substantially. In the other three branches, the following commands fail with the following messages: 
	`forward` (The LOCAL clauses of this POSTCONDITION should not contain any variable)
	`entailer!` (The right hand side is messed up...)
	`localize` (No applicable tactic)

`verif_unionfind.v`, `verif_unionfind_slim.v`, and `verif_unionfind_rank.v`
	`forward_call` goes through but with changes in its behavior. There are a few small things that I'm able to clear easily, but the context has definitely changed. The `forward` that comes soon thereafter is no longer able to find what it needs. The message is the classic "It is not obvious how to move forward here. Find a SEP clause..."

`verif_unionfind_iter.v` and `verif_unionfind_iter_rank.v` 
	`entailer!` now goes through but `localize` still fails soon thereafter. Message: "no applicable tactic"

**Comment by andrew-appel** [comment]
The problem is that your "graph" predicate has type `pred` and not `mpred`.  Although `pred` is convertible with `mpred`, it is not identical, and this confuses many of our tactics.  Although we could adjust many tactics to accommodate, this would slow down Floyd proof automation everywhere.  Therefore I propose to change VST so that you get appropriate feedback when you have a SEP conjunct whose type is not identical to `mpred`.  Then you'll have to adjust your definition of `graph` so that it has exactly type `mpred`.

**Comment by andrew-appel** [comment]
Commit d6824c2  makes the change that I describe above.
