### ISSUE TITLE
CompCert updates

### ISSUE THREAD

**Issue by vbgl** [PrincetonUniversity/VST#335]
In order to make some progress on the Coq development (https://github.com/coq/coq/pull/9811; https://github.com/coq/coq/pull/9854), it would be great if recent changes to CompCert could be incorporated to VST. In particular commits https://github.com/AbsInt/CompCert/commit/7644d49d591799902f50c2240900db4f302ceff5 and https://github.com/AbsInt/CompCert/commit/e9c136508ee6e51f26d280ac17370d724b05bf41. Thanks.

**Comment by andrew-appel** [comment]
Done.

**Comment by vbgl** [comment]
Thank you very much!

Apparently, this breaks a few things though:

> COQC compcert/lib/Integers.v
File "./compcert/lib/Integers.v", line 19, characters 22-27:
Error: Unable to locate library Zbits.

**Comment by andrew-appel** [comment]
Missing file Zbits corrected in latest commit.
