### ISSUE TITLE
sc_set_load_store.load_tac hidden error messages

### ISSUE THREAD

**Issue by andrew-appel** [PrincetonUniversity/VST#339]
This line of` Ltac load_tac`,

` first [ load_tac_with_hint LOCAL2PTREE | load_tac_no_hint LOCAL2PTREE | SEP_type_contradict LOCAL2PTREE Delta e R | hint_msg LOCAL2PTREE Delta e];
`

has the unfortunate effect of hiding some of the error messages in `load_tac_no_hint`, in particular these two:

```
  | (solve_msubst_eval_LR                   || fail 1 "Cannot evaluate right-hand-side expression (sometimes this is caused by missing LOCALs in your precondition)")
  | (solve_msubst_efield_denote             || fail 1 "Cannot evaluate right-hand-side expression (sometimes this is caused by missing LOCALs in your precondition)")
```

One solution is to change `fail 1` to `fail 1000`,  but I am not sure if that will break some sort of intentional fail-over  to SEP_type_contradict or hint_msg.

If you do change `fail 1` to `fail 1000`, do it in load_tac_with_hint as well.

**Comment by QinxiangCao** [comment]
OK, I will take care of this.

**Comment by QinxiangCao** [comment]
"fail 1" here should be a tactic bug. Theoretically, changing it to "fail 1000" should work, without breaking anything else. I tested all "progs" files on my laptop. Travis will do some other testing.

**Comment by bcip** [comment]
Is it better to use a particular level, maybe 3, to make the user level tactic be fail 0?
