### ISSUE TITLE
forward does not give hint when failing

### ISSUE THREAD

**Issue by bcip** [PrincetonUniversity/VST#343]
In verif_swtich.v, line 39, if user doesn't know how to proceed on switch clause after start_function, she will use hint or forward to figure out what to do. `hint` says
> Hint: try 'forward', which may tell you (in an error message) additional information about what to do.

`forward` says
> In nested Ltac calls to "forward" and "forward1", last call failed.
> No matching clauses for match.

I suspect there are more cases that forward doesn't hint, after I change fail level to work with `step`.

**Comment by andrew-appel** [comment]
Fixed.
