### ISSUE TITLE
Makefile bug for progs/pile data abstraction example

### ISSUE THREAD

**Issue by dnaumann** [PrincetonUniversity/VST#361]
I copied pile/* and created CONFIGURE file as per pile/README.md.
The build failed because grep uses a hard coded path instead of COMPCERT_LOC.  
Also, the path refers to name 'compcert' but distributions of compcert have root directories
named like CompCert-3.5, so the version is in $(COMPCERT_LOC)/VERSION. The Makefile correctly uses $(COMPCERT_LOC)/clightgen.

FYI after fixing Makefile I got the following error, which turns out to be my fault but puzzling.
-----------------
> make -j7 link_pile.vo
make: *** No rule to make target `fast/fastpile.c', needed by `stdlib.v'.  Stop.
-----------------
Methinks there's something wrong with the dependencies, since as per the README this 
build target isn't for the fast version.  It's also puzzling that stdlib would depend
on its clients.  But the error went away when I copied the fast/* subdirectory,
which I had not initially done.

Another remark: I needed to delete the "-R pile" from VST_FLAGS in order to interactively walk through the proofs after building.  Otherwise, for example, the import of main in spec_main would fail because it had been built as pile.main.

**Comment by andrew-appel** [comment]
We are now building this example using the VSU system, as progs/VSUpile and progs64/VSUpile.  We have stopped supporting the progs/pile version of this verification.  I have documented that fact by putting an error message in progs/pile/Makefile, in commit [0c4670d](https://github.com/PrincetonUniversity/VST/commit/0c4670d01127d5f6eb13a86df4500d025437bb21).  So I will close this issue report.
