### ISSUE TITLE
long negation fails typecheck

### ISSUE THREAD

**Issue by vzaliva** [PrincetonUniversity/VST#377]
How to reproduce:

`Compute (isUnOpResultType Oneg (Etempvar _value tlong) tlong).`  

Returns `FF(bottom)`.

We traced the problem to  [isUnOpResultType](https://github.com/PrincetonUniversity/VST/blob/4b2cad534e0765f5e92f8895899f4aaea920869c/veric/expr.v#L416) definition which does not handle `neg_case_l`.

I beleive that according to C99 standard it should typecheck as `long`.

However I acknowledge this behaviour could be problematic as `abs(LONG_MIN) > LONG_MAX` so result may not fit. This seems like undefined behaviour. `gcc` handles this as follows:

```
$ cat test.c

#include <limits.h>
#include <stdio.h>

int main()
{
    long a = LONG_MIN;
    long b = -a;
    printf("%ld\n%ld\n", a, b);
}

$ gcc -m32 -O0 -std=c99 test.c
$ ./a.out                                                                     
-2147483648
-2147483648
```

Please note, the compiler does not give compile-time typing error.
Even while the behaviour is undefined for some values, typechecking for it is well defined.
Also the same test program will work for other values besides `LONG_MIN`.

(originally reported by @p3rsik )

**Comment by vzaliva** [comment]
Relevant C99 standard quote:

_6.5.3.3-1 The result of the unary - operator is the negative of its (promoted)
operand. The integer promotions are performed on the operand, and the
result has the promoted type._

**Comment by andrew-appel** [comment]
I just committed to the master branch a fix for this problem, but I don't have your exact test case to try it on.  Can you tell me if this is satisfactorily resolved?  (And if so, close the issue report)

**Comment by vzaliva** [comment]
Thanks! We will check and report back. We are a few versions behind _master_ since we are using OPAM version of VST.

**Comment by akinanop** [comment]
I attach the minimal test case. Tried with the fix, now the type-checking works. Thanks!
[long_bug.zip](https://github.com/PrincetonUniversity/VST/files/3868702/long_bug.zip)

**Comment by vzaliva** [comment]
looks like it is fixed now. Thanks!
