### ISSUE TITLE
No version tag created for 2.5

### ISSUE THREAD

**Issue by MSoegtropIMC** [PrincetonUniversity/VST#383]
I am currently editing the "addon" version picks for Coq 8.11. Since the latest tag 2.4 is a bit old I looked around a bit and found commit:

795521078a8c087fc7d3bb192f2943d0f831b125

which changes the VST version number to 2.5. I assume that is just has been forgotten to tag this commit as v2.5 and will use this commit as pick for Coq 8.11. In case this is what you want, please create a tag 2.5 for this commit. Otherwise please let me know what I should pick.

**Comment by andrew-appel** [comment]
I did not forget.  I changed the internal version number in advance of a v2.5 release.  We have not done a v2.5 release; the last public release is v2.4.  If you can wait 3 days, I can discuss with the VST team whether we want to make a 2.5 release this week, or wait a few weeks; then you can decide whether to use 2.4 or 2.5.

**Comment by MSoegtropIMC** [comment]
Thanks for the information! I guess that the Coq 8.11 RM (@ppedrot) can't wait that long. Let me see if 2.4 works with 8.11.

Btw.: we are working on decoupling the Coq core releases and the platform / installer release, so that this can be done in a more controlled and less hurried way in the future.

**Comment by andrew-appel** [comment]
If 2.4 does not work with 8.11, then I might consider releasing a v2.5 today based on the current master branch; just let me know.

**Comment by MSoegtropIMC** [comment]
I just tested 2.4 and it fails at:
```
File ".\compcert/flocq/Prop/Relative.v", line 569, characters 2-68:
Error: Found no subterm matching "(/ 1)%R" in the current goal.
```
It looks like 2.4 was before the changes in the field tactic.

In the Coq 8.10.X branch the picking comments for VST read see (https://github.com/coq/coq/blob/v8.10/dev/ci/ci-basic-overlay.sh):
```
# Latest tag 2.4 does not compile with Coq 8.10 cause of changes in field
# and the fix of template-poly bug (PR#9918)
# 220a3a7da09f8a523c01a6703c6db098cee8d8d2 is latest as of August 6th.
```
so there seem to be more issues than just the field tactic.

If you want to release 2.5, tomorrow would also be fine. I told @ppedrot upfront that the picking will likely take until tomorrow and he was fine with this. I do a preliminary commit with the VST commit I mentioned.

**Comment by andrew-appel** [comment]
I have just tagged the current master branch (with no changes) as v2.5.

**Comment by MSoegtropIMC** [comment]
Perfect, thanks!
