### ISSUE TITLE
A problem of forward_call subsumption.

### ISSUE THREAD

**Issue by QinxiangCao** [PrincetonUniversity/VST#385]
In the attached example, we (Litao Zhou and I) want to use the subsumption version of forward_call. But it fails at the following command:
              forward_call dfs_subsume (G, v0, Gsh, Vsh).

[demo.zip](https://github.com/PrincetonUniversity/VST/files/4112276/demo.zip)

**Comment by lennartberinger** [comment]
Resolved.
