### ISSUE TITLE
Allow installing dependencies via OPAM

### ISSUE THREAD

**Issue by liyishuai** [PrincetonUniversity/VST#389]
https://github.com/PrincetonUniversity/VST/blob/64dac6db747978cdcc0919691d1ba2ae8a32d0d0/Makefile#L88-L99
The current `Makefile` requires dependencies to be cloned into subdirectories and installed locally, which is less automatic than using OPAM, and introduces nontrivial effort to include _Verifiable C_ in _Software Foundations_' CI.
Is it worth replacing the submodules with a `coq-vst.opam` file so that `opam install --deps-only .` takes care of all dependencies, and write another script for developers that never want OPAM on their machines? The submodules seem to break OPAM unexpectedly.

**Comment by andrew-appel** [comment]
This issue should be resolved by pull request #406.
