### ISSUE TITLE
BUILD_ORGANIZATION.md lists wrong Coq version

### ISSUE THREAD

**Issue by HazardousPeach** [PrincetonUniversity/VST#391]
The file BUILD_ORGANIZATION.md, linked from the main README.md as instruction on how to build the project, says that VST uses Coq 8.7.1. However, if you install Coq 8.7.1 and try to run `make`, you get the message
```
Makefile:447: *** FAILURE: You need Coq 8.10.1 or-else 8.10.0 or-else 8.10+alpha but you have this version: The Coq Proof Assistant, version 8.7.1 (March 2020) compiled on Mar 10 2020 17:09:37 with OCaml 4.07.0.  Stop.
```

**Comment by andrew-appel** [comment]
This issue has been resolved.
