### ISSUE TITLE
[coq] build broken in Coq master, VST moved to "allow_failure" mode

### ISSUE THREAD

**Issue by ejgallego** [PrincetonUniversity/VST#392]
For a few days vst has been consistently failing in our CI, this is to notify that per-policy, VST has been moved to the "allow_failure" mode.

We will be happy to re-add it to Coq's required CI when the problem is fixed.

**Comment by andrew-appel** [comment]
This is rather frustrating, especially because the reason that VST's own continuous integration fails is because of Coq incompatibilities with the standard release of ocaml.

In particular, I sent this message to coqdev yesterday:

To: coqdev

This is really an opam question, not a travis-ci question, I hope!

My travis-ci build fails because Travis's installation of ocaml is newer than Coq 8.11 permits.

https://travis-ci.org/PrincetonUniversity/VST/jobs/660791344?utm_medium=notification

Can anyone give me advice?
See line 735 below; and notice that I already tried adding the --unlock-base at line 605.

Sincerely,

Andrew Appel


```
415
docker_mtu
416docker stop/waiting
resolvconf
418resolvconf stop/waiting
apt
420Adding APT Sources
484
0.00s
git.checkout
485
2.55s
$ git clone --depth=3 --branch=master https://github.com/PrincetonUniversity/VST.git PrincetonUniversity/VST
495
496
497Setting environment variables from .travis.yml
498$ export NJOBS=2
499$ export COMPILER="default"
500$ export COQ_VERSION="8.11.0"
501$ export NEXT_VERSION="8.11.0"
502$ export BITSIZE=32
503
rvm
504
3.68s
$ rvm use default
510
cache.1
511Setting up build cache
541
ruby.versions
542$ ruby --version
550
before_install.1
551
0.00s
$ sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
before_install.2
552
3.39s
$ git submodule update --init --recursive
install.1
571
0.01s
$ opam --version
install.2
573
286.53s
$ [ -e .opam ] || opam init -j ${NJOBS} -n -y
install.3
597
$ opam switch list
install.4
603
$ opam switch ${COMPILER}
install.5
605
$ opam switch --unlock-base
install.6
611
$ eval $(opam config env)
install.7
612
$ opam config list
install.8
663
$ opam config var root
install.9
665
$ opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || true
install.10
673
$ opam repo add coq-released https://coq.inria.fr/opam/released
install.11
681
$ opam update
install.12
687
$ opam show coq
727
$ travis_wait 15 opam install -j ${NJOBS} -y coq=${COQ_VERSION} ${EXTRA_OPAM}
728
729
730Still running (1 of 15): opam install -j 2 -y coq=8.11.0
731The command opam install -j 2 -y coq=8.11.0 exited with 20.
732
733Log:
734
735The following dependencies couldn't be met:
736 - coq → ocaml < 4.10
737 base of this switch (use `--unlock-base' to force)
738
739No solution found, exiting
740/home/travis/.travis/functions: line 607: 16488 Terminated travis_jigger "${!}" "${timeout}" "${cmd[@]}"
741The command "travis_wait 15 opam install -j ${NJOBS} -y coq=${COQ_VERSION} ${EXTRA_OPAM}" failed and exited with 20 during .
742
743

```

**Comment by ejgallego** [comment]
Hi @andrew-appel , indeed Coq doesn't support OCaml 4.10 yet; we have been trying to get it supported for months (c.f, https://github.com/coq/coq/issues/10726 , https://github.com/coq/coq/pull/11131 , https://github.com/coq/coq/pull/11102 ) but it is still not there.

I am curious tho why you are using such a recent OCaml release, do you have a need for a 4.10 specific feature?

Otherwise I'd recommend staying in 4.07.1 (flambda) if you can, there still are some performance issues with the GC in OCaml >= 4.08 that are affecting Coq.

**Comment by andrew-appel** [comment]
I am not using such a recent ocaml release.  The problem is that travis-ci has the most recent ocaml installed.  For that reason, my travis script fails to install Coq via opam.  I am not an opam expert, so I don't know how to fix this.  The fix suggested by opam (in the travis output at line 735) does not seem to work; that is, I added the line 605 (opam switch --unlock-base) to my travis configuration, but it didn't fix anything.

**Comment by ejgallego** [comment]
I see, I'd suggest changing the `COMPILER` variable in `.travis.yml` from `default` to a concrete version.

I'd suggest 4.07.1 in this case [you are welcome to experiment with `4.07.1+flambda` to see if you get a speedup)

**Comment by ejgallego** [comment]
Something we've learned in Coq's CI is to always "pin" all our dependencies, as to obtain a fully deterministic CI environment.

**Comment by ejgallego** [comment]
Also note @andrew-appel that using Coq's [Docker CI images](https://github.com/coq-community/docker-coq) could be pretty convenient for you; that provides a pre-built Coq developer environment which is quite convenient to use and tends to save time.

[Another interesting alternative is Nix, but that requires more specialized knowledge as to install]

@Zimmi48 @SkySkimmer maybe we should improve a bit the `doc/ci/README-users.md` guide ? We could even provide templates? [or that would make sense in the Nix / Docker repos and then point to them?]

**Comment by Zimmi48** [comment]
The coq-community templates can be used by any project but they would deserve some more documentation. In any case, the Docker-based CI is pretty well documented and link to its documentation has just been added to the file mentioned above. cc-ing @erikmd who maintains these images.

**Comment by ejgallego** [comment]
@andrew-appel seems like Travis is back running, thank you!

The error is similar to what we get in Coq's CI:
```
File "./veric/SeparationLogicSoundness.v", line 164, characters 27-46:
Error:
In environment
CS : compspecs
Espec : OracleKind
Delta : tycontext
A : TypeTree
P : forall ts : list Type, dependent_type_functor_rec ts (ArgsTT A) mpred
Q : forall ts : list Type, dependent_type_functor_rec ts (AssertTT A) mpred
NEP : args_super_non_expansive P
NEQ : super_non_expansive Q
ts : list Type
x : dependent_type_functor_rec ts A mpred
F : ?T
ret : option ident
argsig : list type
retsig : type
cc : calling_convention
a : expr
bl : ?T0
rho : environ
The term "tc_expr Delta a rho" has type "mpred"
while it is expected to have type "bool".
```
it could be a bug in VST or a regression in Coq master, however I could reproduce with Coq 8.11 so the first seems more likely.

**Comment by andrew-appel** [comment]
Please put VST  back in Coq's CI without "allow-failure" mode.  VST's master branch now works in Coq 8.11, _**and**_  VST's own continuous integration script is repaired so that this kind of failure should not happen again.

Thanks to advice from @ejgallego, I was able to fix VST's travis-ci opam-installation script.  Consequently I was able to discover why VST has been failing in Coq 8.11 recently, and fix it.

(By the way, I don't use Docker in travis-ci, because that would prohibit the use of make -j2; which would cost us a factor of 2 in travis-ci performance.)

I do have one remaining Coq/opam question:  Based on advice, I have pinned my CI script to use ocaml 4.07.1 to compile Coq 8.11.0.    When some future version of Coq requires (or suggests) a later version of ocaml, how will I learn that?  That is, what should the procedure be for updating my CI script?

**Comment by ejgallego** [comment]
> Please put VST back in Coq's CI without "allow-failure" mode.

Will put back later today, thank you @andrew-appel 



> (By the way, I don't use Docker in travis-ci, because that would prohibit the use of make -j2; which would cost us a factor of 2 in travis-ci performance.)

Oh that's surprising, I was not aware of this restriction, you can run arbitrary docker commands inside the docker switch so I'm not sure why `make -j 2` wouldn't work there. Note that using flambda can provide a non-trivial perf jump if you are worried about build time.

Also note that it's been a while since I work with Travis runners, but most providers are back to 1-core machines tho [for example gitlab]

> I have pinned my CI script to use ocaml 4.07.1 to compile Coq 8.11.0. When some future version of Coq requires (or suggests) a later version of ocaml, how will I learn that? That is, what should the procedure be for updating my CI script?

4.07.1 should be fine for a reasonably long time; would we bump the minimal OCaml version the opam install of Coq would fail with an unsatisfied dependency constraint, that would still require manual intervention but at least the error message should be easy to understand.

Coq's Docker images do take care of this problem for you, as they provide pre-configured `base` and `edge` images.

**Comment by andrew-appel** [comment]
Regarding travis-ci and docker, this link shows that non-docker configurations can use 2 cores:
https://docs.travis-ci.com/user/reference/overview/#virtualization-environments

Two or three years ago, I remember reading that with Docker in travis-ci one cannot use multicore, but I don't know where the documentation says that now.

**Comment by ejgallego** [comment]
> Regarding travis-ci and docker, this link shows that non-docker configurations can use 2 cores:
> https://docs.travis-ci.com/user/reference/overview/#virtualization-environments
> 
> Two or three years ago, I remember reading that with Docker in travis-ci one cannot use multicore, but I don't know where the documentation says that now.

I can see no restriction there, maybe you are thinking of the deprecated "container boot"?

Getting to use a docker image is just as easy as declaring `service: -docker` and it doesn't seem to impose any restriction on the GCE worker, c.f. https://docs.travis-ci.com/user/docker/

[Here's](https://github.com/erikmd/docker-coq-travis-ci-demo-1/blob/master/.travis.yml) a Coq Docker Travis CI template if you would like to try and compare build times, etc...

The template is self-explanatory IMO.

**Comment by ejgallego** [comment]
An interesting side-effect of this setup is that once you got it running it becomes fairly easy to distribute VST Docker images, I wonder if that could be useful for you, more info at: https://github.com/erikmd/docker-coq-travis-ci-demo-2

[I'm not sure Travis limits would allow VST to build in full tho]

**Comment by ejgallego** [comment]
I can't reopen this it seems, but the build is again broken in 8.11 / 8.12+alpha.

**Comment by andrew-appel** [comment]
How embarrassing!  Fixed now.  I had been trying a complicated semi-merge of the master branch with the concurrency branch, and I didn't realize that broke the master branch in the process.

**Comment by ejgallego** [comment]
Thank you @andrew-appel !

Coq is still quite slow so it is normal sometimes it is not possible to check manually every commit compiles; hopefully work improving incremental compilation will be ready soon, reducing checking time.
