### ISSUE TITLE
External CompCert doesn't build

### ISSUE THREAD

**Issue by LukeXuan** [PrincetonUniversity/VST#403]
The `COMPCERTDIRS` variable in `Makefile` needs to include `flocq` for external CompCert library.

**Comment by andrew-appel** [comment]
That's half true.  Near-future versions of CompCert may permit a configuration option so that even an external CompCert permits using an external flocq.  I have to think about how to handle this.

**Comment by andrew-appel** [comment]
For now I have updated BUILD_ORGANIZATION to document what to do in option B.
