### ISSUE TITLE
Flocq problem for VST on mac (coq-8.11.0-installer-macos.dmg)

### ISSUE THREAD

**Issue by QinxiangCao** [PrincetonUniversity/VST#414]
Currently, Flocq cannot be correctly imported on mac if users install coq via a mac package coq-8.11.0-installer-macos.dmg. See my coq bug report here: https://github.com/coq/coq/issues/12275

Somehow mac's CoqIDE is not very popularly used; people can easily install emacs + PG, although three of my students use the .dmg approach to install. I don't think it is a very big problem for VST.

What shall we do? I propose not to do anything because Coq will hopefully solve this problem in their next version. For my students (and other potential users) who use Mac's CoqIDE, my suggestion is to temporarily modify several VST's files for now:

1. Makefile. Choose "FLOCQ=flocq  # this mode to use the flocq built into compcert" on line 85.
2. Comment out "From Flocq" from the following files: 
compcert/lib/Floats.v
compcert/lib/IEEE754_extra.v
compcert/x86_32/Archi.v
compcert/x86_64/Archi.v
veric/superprecise.v

**Comment by andrew-appel** [comment]
I expect this problem will be entirely solved by pull request #406.

**Comment by andrew-appel** [comment]
@QinxiangCao , is this issue still a problem, or can we close it?

**Comment by anshumanmohan** [comment]
Probably worth waiting for @QinxiangCao's reply, but I used to need the Flocq modifications and no longer need them.
