### ISSUE TITLE
accessing and modifying the bit-representation of a floating-point number

### ISSUE THREAD

**Issue by andrew-appel** [PrincetonUniversity/VST#429]
See also https://github.com/AbsInt/CompCert/issues/207.

Consider this program:
```
union {float f; unsigned int i; } u;
...
int a,b; float x,y;
u.f = x;
a = u.i;
b = fiddle(a);
u.i = b;
y = u.f;
```
This is _exactly_ the pattern used by floating-point functions such as `fabs` and `sqrt`:  That is, given a floating-point value `x`, convert it to its bit-representation `a`,  then do some transformation on the bit-representation yielding `b`, then convert that to a floating-point value `y`.  For `fabs`, the transformation is to set the sign bit to 0; for `sqrt`, the transformation is to shift the exponent right by one bit (and after that, there is still some work to do on the mantissa by ordinary floating-point calculation).

One could also imagine doing this by casting (int*) to (float*) and back, but this produces undefined behavior in C (even though some programmers still do it); that is, C compilers are permitted to consider different-typed pointer variables as definitely-not-aliased, which wouldn't be the case here.  Using a union as shown above is the official way to do this in C.

The sequence `u.f=x; a=u.i` can be proved correct in VST to a strong enough specification to be useful in verifications of function such as `fabs` and `sqrt`, **but the sequence `u.i=b; y=u.f` _cannot_ be proved correct in the current Verifiable C logic.**  

The problem lies in the way that CompCert stores integer values in memory, and the CompCert semantics' internal `memval` datatype.  A 4-byte integer may be stored as a sequence of Byte memvals, or as a sequence of Fragment memvals.  When loading such an integer with chunk-type Mint32, the `decode_val` function knows how to reassemble either Byte or Fragment values.  But when loading such an integer with chunk-type Vsingle, it expects only Byte values.

For a formal derivation that explains the issue, look in progs/verif_union.v;  the lemma `decode_float32_int32` is proved, but the lemma `NOT_decode_int32_float32` demonstrates that the opposite direction is false.

There are two possible solutions: (1) change CompCert's semantics, or (2) put a hack in VST.  Since the CompCert designers do not wish to change their semantics, I will suggest how solution (2) might work.

The proposed solution is to make a special-case VST proof rule for the two-command sequence, `u.i=b; y=u.f;`.  That is, a Hoare triple approximately like,
```
{writable_share sh && data_at_ sh (Tunion u) p}
u.i=b; y=u.f;
{y=float32_of_int32(b) && data_at_ sh (Tunion u) p}
```
where 
```
Definition float32_of_int32 (i: int) : float32 :=
 Float32.of_bits (Int.repr (int_of_bytes (bytes_of_int 4 (Int.unsigned i)))).
```

This proof rule is admittedly ugly and not very general.  However, it is general enough to handle the important case, used in several functions of the floating-point library, of using a union to manipulate the bit-representation of a floating-point number.

This rule can be proved foundationally sound w.r.t. the CompCert semantics.  The reason it avoids the Fragment pitfall is that the load _immediately_ follows the store, with no function calls in between.  In function calls to unknown code, spilling in those functions may convert the Byte memvals to Fragment memvals, but in this special case of two commands in a row, that (provably) will not happen.

The converse rule, for the command `u.f=x; a=u.i`  does not need special treatment, because (as I said above) it can be proved correct now in VST.

One would also need a corresponding rule for double-precision floating point (Vfloat, int64).

**Comment by xavierleroy** [comment]
Sounds good!

In the CompCert memory model there's a theorem `Memory.load_store_similar` that captures what happens when loading after a store but with a different type.  The value that is read is related to the value that was written by the `Memdata.decode_encode_val` predicate
https://github.com/AbsInt/CompCert/blob/375c844efb8b91d4ff1dce08ed25f55ddef231d7/common/Memdata.v#L457
It "knows about"  int <-> float reinterpretations at sizes 32 and 64 bits, but also other reinterpretations such as unsigned char <-> signed char.  Maybe this could helo making the new proof rules more general.

**Comment by xavierleroy** [comment]
>  In function calls to unknown code, spilling in those functions may convert the Byte memvals to Fragment memvals, but in this special case of two commands in a row, that (provably) will not happen.

Another workaround could be to have a stronger postcondition for the assignment `u.i = b`:
```
    { ... } u.i = b { u.i contains integer b /\ u.f contains FP32 number float32_of_int32(b) }
```
Presumably, the function calls to unknown code will preserve the "contains" relation, so the load from `u.f` could happen later, not just immediately after the assignment to `u.i`, yet still produce the correct value.

**Comment by andrew-appel** [comment]
Done.
