### ISSUE TITLE
Improve go_lower0

### ISSUE THREAD

**Issue by jldodds** [PrincetonUniversity/VST#43]
I've seen at least one case where go_lower does quite a bit of autorewriting after ```go_lower0``` has already made the goal trivially solvable (```_ |-- !!True```). It might be worth trying to solve these at this point. 

I saw this in the call to entailer after semac_SC_set is applied, which could probably be ```quick_typecheck``` instead

**Comment by andrew-appel** [comment]
Resolving this by calling quick_typecheck3 from the tactic that applies semax_SC_set1.  (quick_typecheck3 was already used in the load and store tactics, and also a bug
in quick_typecheck3 was just fixed yesterday by Qinxiang.)  Resolution will appear in the next commit.
