### ISSUE TITLE
OPAM CompCert does not have Makefile.config

### ISSUE THREAD

**Issue by andrew-appel** [PrincetonUniversity/VST#433]
When used with an external CompCert, VST configures itself by looking at CompCert's Makefile.config to learn the target architecture and BITSIZE.  But when CompCert has been installed with Opam, there is no Makefile.config present.  Thus, VST does not build properly.

Thanks to @ybertot for reporting this.

**Comment by MSoegtropIMC** [comment]
This should be fixed by https://github.com/PrincetonUniversity/VST/pull/406.

**Comment by MSoegtropIMC** [comment]
To further clarify this:

an installed CompCert provides a file called compcert.config which contains equivalent information to Makefile.config but is specifically intended for use by Coq makefiles, while Makefile.config was more a CompCert internal file.

This is supported by the `coq-compcert.3.7~coq-platform` series of packages and will also be supported by the main (non platform) compcert.3.8 package. VST should anyway use the coq-platform variants of CompCert, which use the platform supplied Flocq.

The new Makefile uses compcert.config, so I would consider this as fixed.
