### ISSUE TITLE
tactic always timed

### ISSUE THREAD

**Issue by anshumanmohan** [PrincetonUniversity/VST#456]
`(change (construct_fold_right_sepcon_rec emp X Y))` inside of `floyd/seplog_tactics.v` is always timed, which makes builds messy. Just a stray call to `time`?

**Comment by andrew-appel** [comment]
Indeed.  As I developed the fix to issue #452, I wanted to make sure that it was efficient (which it is!).  But then I forgot to take out the time command.  I'll fix this today.

**Comment by anshumanmohan** [comment]
Thanks!
