### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.13

### ISSUE THREAD

**Issue by gares** [PrincetonUniversity/VST#461]
The Coq team is planning to release Coq 8.13-beta1 on December 7, 2020
and Coq 8.13.0 on January 7, 2020.

Your project is currently scheduled for being bundled in the Windows installer.

We are currently testing commit ebcd978765a8211d545c8efd2114dec75a991720
on branch https://github.com/PrincetonUniversity/VST/tree/master
but we would like to ship a released version instead (a tag in git's slang).
Moreover we would like VST to be compatible with compcert 3.8, since we
plan to ship that version.

It would be awesome if you could provide a tag that works both with compcert 3.8
and with the Coq branch v8.13, possibly 15 days before the date of the final release.

Thanks!
CC: https://github.com/coq/coq/issues/12334 @MSoegtropIMC

**Comment by andrew-appel** [comment]
VST (master branch) already works with CompCert 3.8, and we intend to provide a VST tag v2.7 by December 15th, assuming that Coq v8.13beta is released on December 7.

**Comment by gares** [comment]
Thanks for the tag!
