### ISSUE TITLE
Type punning is not supported

### ISSUE THREAD

**Issue by akinanop** [PrincetonUniversity/VST#463]
C ISO 99 standard supports so-called "type punning", but VST doesn't. Here is a small example:

```
 char *f(const char *x) {
  union {
    const char *x;
    char *y;
  } t;

  t.x = x;

  return t.y;
} 
```

Here we're using union type to get rid of `const `modifier by accessing second field with the same type but without `const`.

Small example in VST:
```
Require Import VST.floyd.proofauto.
Require Import example.

Definition Vprog : varspecs. mk_varspecs prog. Defined.
Instance CompSpecs : compspecs. make_compspecs prog. Defined.

Open Scope Z.

Definition f_spec : ident * funspec :=
  DECLARE _f
    WITH x : val
    PRE [tptr tschar]
      PROP ()
      PARAMS (x)
      GLOBALS ()
      SEP (data_at_ Tsh (tptr tschar) x)
    POST [tptr tschar]
      PROP ()
      LOCAL ()
      SEP ().

Definition Gprog := ltac:(with_library prog [f_spec]).

Theorem test : semax_body Vprog Gprog f_f f_spec.
Proof.
  start_function.
  forward.
  forward.
  (* if you run entailer! here, you'll get False, which is unprovable *)
  entailer!.
Admitted.
```
If you run this coq code, you'll get to unprovable goal where VST checks whether we're trying to get initialized field from union. It looks as follows:
```
  ENTAIL Delta,
  PROP ( )
  LOCAL (lvar _t (Tunion __136 noattr) v_t; temp _x x)
  SEP (data_at Tsh (Tunion __136 noattr) (inl x) v_t; data_at_ Tsh (tptr tschar) x)
  |-- local (liftx (tc_val (tptr tschar) Vundef))
```
which transforms into `False` by `entailer!` tactic.

So, the questions are:

1) Why VST represents unions as disjoint sum?

2) Is this feature (type punning) not supported by VST?

3) Are there any workarounds around this issue excluding editing C code?

**Comment by andrew-appel** [comment]
This program is provable, but VST is not as helpful as it could be. 
First, I notice that in VST 2.7 the `try_forward_store_union_hack` tactic is misfiring (and isn't needed), so part 1 of the workaround is to disable it by,
`Ltac try_forward_store_union_hack ::= idtac.`
The purpose of `try_forward_store_union_hack` is to support type punning between int and float, as demonstrated in progs/union.c in the function `fabs_single`.  

For your purpose, you can prove this lemma:

```
Lemma pun_const_char_star:
  forall (x: val) v, 
      data_at Tsh (Tunion __138 noattr) (inl x) v =
      data_at Tsh (Tunion __138 noattr) (inr x) v.
Proof. intros. reflexivity. Qed.
```

and then after the first `forward` command you can `rewrite pun_const_char_star`.

I will leave this issue-report open until I diagnose why the "forward store union hack" is getting in the way here, and perhaps I can generalize to handle cases like this as well.
