### ISSUE TITLE
Universe inconsistency if Princeton VST and QuickChick is required

### ISSUE THREAD

**Issue by MSoegtropIMC** [PrincetonUniversity/VST#488]
Dear VST Team,

when I write:
```
Require Import QuickChick.QuickChick.
Require Import VST.floyd.proofauto.
```
I get: `Universe inconsistency. Cannot enforce sig.u0 < eq.u0 because eq.u0 <= sig.u0.`

When I write:
```
Require Import VST.floyd.proofauto.
Require Import QuickChick.QuickChick.
```
I get:
```
Universe inconsistency. Cannot enforce eq.u0 = QuickChick.Sets.40 because QuickChick.Sets.40 <= QuickChick.Sets.8
<= Coq.Relations.Relation_Definitions.1 <= sig.u0 < eq.u0.
```

This is with:
```
coq-quickchick           1.5.0       Randomized Property-Based Testing Plugin for Coq
coq-vst                  2.7         Verified Software Toolchain
```
(the versions in Coq Platform 2021.02).

I first posted this at QuickChick (https://github.com/QuickChick/QuickChick/issues/220), and their analysis is that the universe constraint `sig.u0 < eq.u0` produced by VST is unexpected.

Best regards,

Michael

**Comment by andrew-appel** [comment]
When I do `Print Universes` on an empty buffer with nothing at all imported, it shows the constraint `sig.u0 < eq.u0` . So I don't understand the claim that this is coming from VST.

**Comment by QinshiWang** [comment]
Maybe this comes from VST?
`Coq.Relations.Relation_Definitions.1 <= sig.u0`

**Comment by andrew-appel** [comment]
The bad constraint (sig.u0 < eq.u0) was introduced by the f_equal tactic.  I made a better f_equal tactic that avoids it.  See the explanation in commit 07bc0ee.
