### ISSUE TITLE
Reroot, fold_data_at

### ISSUE THREAD

**Issue by QinxiangCao** [PrincetonUniversity/VST#49]
In principle, users should not unfold a data_at when doing load/store operations. Reroot_field/reroot_array is used before function call and fold_data_at is used after function.

unfold_data_at/unfold_field_at and split_array are also offered for manual operations.
array_at_len_0 and array_at_len_1 might also be useful.
field_at_data_at and array_at_data_at are the reroot lemmas and users can also use them for manual operations.

Unfold_data_at (also unfold_field_at): unfold one layer down. Leaf cases cannot be unfolded. Array cases are unfolded to array_at.
split_array split an array into two parts.
reroot tactics will (1) apply unfold and split recursively (2) rewrite field_at_data_at or array_at_data_at to finish the reroot process.
fold_data_at will (1) find all related field_address and field_address0 and reverse related data_at back to field_at or array_at (2) fold data_at back recursively

**Comment by QinxiangCao** [comment]
This will be realize by a combination of ramification rule and freezer.

**Comment by andrew-appel** [comment]
load/store operations (for several years now) do not need to unfold data_at.
