### ISSUE TITLE
`msubst_denote_tc_assert` changes signedness of constants in 64 bit + 32 bit additions

### ISSUE THREAD

**Issue by MSoegtropIMC** [PrincetonUniversity/VST#500]
In the verification of the following C program:
```
long test(long val)
{
    return val + 0x80000000;
}
```
VST asks at some point to prove:
```
emp |-- !! (Int64.min_signed <= val + -2147483648)
```
In this term the constant `0x80000000` changed to a **signed** constant, but C (and CompCert) treat it as **unsigned**.

This can be tracked down to this match from `msubst_denote_tc_assert`:
```
  | tc_nosignedover op e1 e2 =>
      denote_tc_nosignedover op (force_val (msubst_eval_expr Delta T1 T2 GV e1))
        (force_val (msubst_eval_expr Delta T1 T2 GV e2))
```
For an unsigned constant, the argument to `denote_tc_nosignedover` evaluates to:
```
Eval simpl in (force_val (msubst_eval_expr Delta PTree.Leaf PTree.Leaf None (Econst_int (Int.repr (-2147483648)) tuint))).
(* = Vint (Int.repr (-2147483648)) *)
```
At this point the information if the constant was signed or unsigned is lost. The evaluation of `denote_tc_nosignedover` then yields:
```
Eval simpl in denote_tc_nosignedover Z.add (Vlong (Int64.repr val)) (Vint (Int.repr (-2147483648))).
(* = !! (Int64.min_signed <= Int64.signed (Int64.repr val) + Int.signed (Int.repr (-2147483648)) <= Int64.max_signed) *)
```
In the end the expression given in `msubst_denote_tc_assert` only works if both operands have the same size, so that the signed / unsigned question does not matter. For 64 + 32 bit additions of both constants and variables, the signedness does matter. Also with other operations than addition things might be even more complicated.

I attached is a zip with the C and Coq files: [Archive.zip](https://github.com/PrincetonUniversity/VST/files/6554180/Archive.zip)

**Comment by andrew-appel** [comment]
I believe that VST is correct here.
CompCert translates `return val + 0x80000000;` as,
```
(Sreturn (Some (Ebinop Oadd (Etempvar _val tlong)
                 (Econst_int (Int.repr (-2147483648)) tuint) tlong)))
```
That is, (Int.repr 0x80000000) is a 32-bit unsigned integer constant (tuint).
Then the add is done as a signed 64-bit integer add (tlong), so there is an implicit cast from (unsigned 32-bit) tuint to (signed 64-bit) tlong, _before_ the add is done.

Since the add is signed, it is required not to overflow.   Therefore the test `(Int64.min_signed <= val + -2147483648)` is necessary.

If you had written this C program instead:
```
long test2(long val)
{
  return (unsigned long)val + 0x80000000ul;
}
```
then it would be easy to prove,
```
Definition test2_spec :=
  DECLARE _test2
  WITH i: Int64.int
  PRE [ tlong ]
   PROP() PARAMS (Vlong i) GLOBALS() SEP()
  POST [ tlong ]
   PROP() RETURN (Vlong (Int64.add i (Int64.repr 2147483648))) SEP().
```

**Comment by MSoegtropIMC** [comment]
Indeed, the unsigned int is casted to a singed 64 bit integer before the addition, but an unsigned integer casted to a signed 64 bit integer gives an unsigned value, not a signed value. Also `0x80000000` is an unsigned integer, not a signed one. in C literals are automatically the smallest integer type which can represent them, and literals without `-` are not considered to be negative. So the intermediate value should probably be
```
Vlong (Int64.repr (2147483648))
```
rather than
```
Vint (Int.repr (-2147483648))
```
In the ZIP archive is a sample program with main function. The build script runs it through CompCert's interpreter. One can clearly see in the result that the code adds 2147483648 and not (-2147483648).

And yes, using long constants and/or explicit casts for variables does help to work around this.

**Comment by MSoegtropIMC** [comment]
Btw.: I think this might be different in 2.7.1 and master. E.g. 2.7.1 does not seem to support long constants - the match for `Econst_long` is missing in `typecheck_expr`, but it is there in master:
(https://github.com/PrincetonUniversity/VST/blob/73fe28a6b9aeec736ffdfd2cafb05cb034c02221/veric/expr.v#L696-L698)
(https://github.com/PrincetonUniversity/VST/blob/b533b257464f86459916fb05fc6e67d69a07bbf7/veric/expr.v#L697-L700)
I will do some tests with master.

**Comment by andrew-appel** [comment]
Indeed, support in VST for long constants is very recent.

In carefully reading the C11 specification, I believe that CompCert is translating this correctly.

That is, the expression   `val+0x80000000`  is being translated into Clight as 

`(Ebinop Oadd (Etempvar _val tlong) (Econst_int (Int.repr (-2147483648)) tuint) tlong)`

when you might think it should be translated as

`(Ebinop Oadd (Etempvar _val tlong) (Econst_long (Int64.repr 2147483648) tlong) tlong)`

In section 6.4.4.1.5 of the[ "Committee Draft -- April 12, 2011" of ISO/IEC 9899:201x](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf),  the table on page 64 shows that the hexadecimal constant 0x80000000 is treated _differently_ than the decimal constant 2147483648.

In particular, decimal constants without a trailing "u" or "l" indicator are represented in the first type, from the following list, that can represent them:  int, long int, long long int.   But hexadecimal constants without a trailing "u" or "l" are represented in the first type from this list:  int, unsigned int, long int, unsigned long int, long long int, unsigned long long int.

So I believe CompCert is correct, and I believe VST is correct.   However, the C11 standard (and the C language) can be confusing -- certainly I myself didn't understand this until just now when I consulted the C11 standard.   So I recommend, whenever you write C code, it's a good idea to verify it with a proved-sound program verifier, just to make sure.  :-)

**Comment by MSoegtropIMC** [comment]
Indeed CompCert is correct, but the range check proof obligations VST derives are to my understanding not (at least not in 2.7.1 - I will check in master today). As shown in my initial post, VST converts CompCert`s `(Econst_int (Int.repr (-2147483648)) tuint)` to `Vint (Int.repr (-2147483648))`:
```
Eval simpl in (force_val (msubst_eval_expr Delta PTree.Leaf PTree.Leaf None (Econst_int (Int.repr (-2147483648)) tuint))).
(* = Vint (Int.repr (-2147483648)) *)
```
which strips away the essential information that the term is unsigned. With this, a `+2147483648` is converted into a `-2147483648` in the range check proof obligations. CompCert's interpreter does compute `+2147483648`.

**Comment by andrew-appel** [comment]
But   Int.repr(-2147483648)=Int.repr(2147483648), so no information is lost there.  I believe the problem is that ((long long)0x80000000) is not equal to ((long long)-2147483648) in the C language.   The former is elaborated as ((long long)((unsigned int)0x80000000u)), a positive number, and the latter is elaborated as ((long long)(-2147483648)), a negative number.

**Comment by andrew-appel** [comment]
Yes, it turns out this is a completeness bug in VST.  I will fix this.
