### ISSUE TITLE
Tactic get confused when context contains multiple compspecs

### ISSUE THREAD

**Issue by lennartberinger** [PrincetonUniversity/VST#503]
When the proof context contains not only the computationally avaliable compspecs from the compilation unit under verification but also another one (likely abstract/not computational, as originating from some other unit), floyd tactics (forward etc) appear to occasionally pick the wrong (abstract) one when instantiating (implicit) parameter etc, and hence fail.
Example: line 106 of VSU_Gclient.v in the attachment. Asserting the (wrong) claim that the two compspecs are equal lets the tactics succeed. (tested under branch value_cohere_lemmas).

[MultiCS.tar.gz](https://github.com/PrincetonUniversity/VST/files/6604443/MultiCS.tar.gz)

**Comment by andrew-appel** [comment]
Closed by commit https://github.com/PrincetonUniversity/VST/commit/33e537f88f59cb0161bbf2aad85b0f115b62ffc2
