### ISSUE TITLE
progs64/incr.c makes invalid assumptions

### ISSUE THREAD

**Issue by Lysxia** [PrincetonUniversity/VST#518]
When I compile and run the example program `progs64/incr.c`, which is supposed to increment a variable twice concurrently, I get a result of 1 instead.

The issue is that in pthreads, a mutex must be unlocked by the same thread that locked it, whereas in this program, the main thread locks a mutex to be unlocked by a spawned thread, which is undefined behavior according to the pthreads documentation.

**Comment by mansky1** [comment]
I've been meaning for a while to switch our threads library over to C11 mutexes. Do you know whether they allow the same behavior?

**Comment by Lysxia** [comment]
C11 mutexes seem to inherit the same limitations. But rather than a mutex, wouldn't `thrd_join` (in C11) or a condition variable be a better fit for the purpose here?

**Comment by andrew-appel** [comment]
Neither thrd_join nor a condition variable would fit here.  Condition variables are not synchronizers on their own, they need to be used in conjunction with locks.  For progs64/incr.c, thrd_join could perhaps do the task, but we are trying to demonstrate the principles of programming with "daring" concurrency (as defined by O'Hearn in his paper on Concurrent Separation Logic", and thrd_join is strictly less general than the kind of semaphores we need for that (as used in incr.c).  Perhaps the solution is to code up busy-wait semaphores using C11 atomics, which should be straightforward.

**Comment by andrew-appel** [comment]
Basically, Posix Threads has semaphores (which is what we want here), and C11 threads does not, it only has mutexes (and atomic memory operations from which you could build semaphores).   If we use posix semaphores, then here are the relevant sentences from the man page:

"An unnamed semaphore must be initialized using sem_init(3). It can then be operated on using sem_post(3) and sem_wait(3). When the semaphore is no longer required, and before the memory in which it is located is deallocated, the semaphore should be destroyed using sem_destroy(3)."

**Comment by andrew-appel** [comment]
@mansky1  is this issue now resolved, or easily resolvable?

**Comment by mansky1** [comment]
We're getting close! The `atomic_locks` branch has our custom spinlock, which is intended as a sound replacement for PThreads/C11. I'm almost done one last Iris-in-VST update that will let us derive the existing lock specs from the stronger specs that the custom spinlock satisfies. We could just directly prove that it satisfies both sets of specs, but I want to push the funspec_sub experiment a little further first.
