### ISSUE TITLE
checking for loads in `forward` is too eager

### ISSUE THREAD

**Issue by jmadiot** [PrincetonUniversity/VST#52]
In the statement

    Sset _v (Efield (Ederef e t) _tail t'

`forward` complains:

    The_expression_or_parameter_list_must_not_contain_any_loads_but_the_following_subexpression_is_an_implicit_or_explicit_load_Please_refactor_this_stament_of_your_program

It is probably because `forward1` it is checking with `no_loads_expr` that no loads appear in `(Ederef e t)`.  What it should probably do is only checking that no loads appear in `e`.

**Comment by andrew-appel** [comment]
Fixed, sometime in the last 2 months.
