### ISSUE TITLE
Custom definition of skipn require in floyd symbolic executor?

### ISSUE THREAD

**Issue by lennartberinger** [PrincetonUniversity/VST#558]
It seems the definition of skipn should be duplicated somewhere below forward.
If one says "Opaque skipn" in a client proof to prevent simplification of a user-level term,
Intros won't replace * with ; in the SEP clause, so subsequent forwards will fail.

Maybe the same for firstn....

**Comment by andrew-appel** [comment]
Fixed in by P.R. 564
