### ISSUE TITLE
Check return type

### ISSUE THREAD

**Issue by lennartberinger** [PrincetonUniversity/VST#60]
If return type given in the POST of a function spec does not match the function's
declared return type, at least a warning should be emitted when the function body is verified.
Currently, no error/warning is emitted, resulting in calls to forward_call failing (with a non-informative error message) when clients are verified.

**Comment by andrew-appel** [comment]
Fixed today. in fa4a071d552a7c03ab1eb53b4a9fef2dfefbf663.
