### ISSUE TITLE
`[ERROR] No package named coq-vst found`

### ISSUE THREAD

**Issue by eleehiga** [PrincetonUniversity/VST#612]
When I run `opam install coq-vst` this yields the error `No package named coq-vst found.` Can you guys please assist me with how I can install vst with opam?

**Comment by QinshiWang** [comment]
Hi @eleehiga! You need to first add the catalog of packages.
```
opam repo add coq-released https://coq.inria.fr/opam/released
```
See [here](https://github.com/coq/opam-coq-archive) for more information.

**Comment by eleehiga** [comment]
@QinshiWang Thank you that worked. Perhaps you guys should make that instruction more clear in the installation steps for VST.
