### ISSUE TITLE
no_loads_expr needs to support Esizeof

### ISSUE THREAD

**Issue by roconnor-blockstream** [PrincetonUniversity/VST#62]
at https://github.com/PrincetonUniversity/VST/blob/master/floyd/forward.v#L2257
`Esizeof` needs to be added to support `sizeof` expressions.
Presumably `Ealignof` should be added as well.

**Comment by samuelgruetter** [comment]
Thanks for reporting, should be fixed in https://github.com/PrincetonUniversity/VST/commit/2573e66fc2d757a9426552e5b6e0e9485f1235f6, please let me know if that works for you.

**Comment by roconnor-blockstream** [comment]
It might be good in `test_sizeof` to use sizeof with both an expression argument, as you have done, and a type argument, like `sizeof(int)`.
