### ISSUE TITLE
Please pick the version you prefer for Coq 8.16 in Coq Platform 2022.09

### ISSUE THREAD

**Issue by MSoegtropIMC** [PrincetonUniversity/VST#620]
The Coq team released Coq `8.16+rc1` on June 01, 2022.
The corresponding Coq Platform release `2022.09` should be released before **September 15, 2022**.
It can be delayed in case of difficulties until October 15, 2022, but this should be an exception.

This issue is to inform you that the opam package we are currently testing in Coq Platform CI **works fine** with Coq `8.16+rc1`.

Coq Platform CI is currently testing opam package `coq-vst.2.10`
from platform patch repository https://github.com/coq/platform/tree/main/opam/opam-coq-archive/released/packages/coq-vst/coq-vst.2.10/opam.  **This means we had to weaken some version restrictions in the opam package, but no other changes were required.**

**In case this is the version you want to see in Coq Platform, there is nothing to do for you - please just close this issue.**

In case you would prefer to see an updated or an older version in the upcoming Coq Platform `2022.09`, please inform us as soon as possible and before **August 31, 2022**!

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.16+rc1~2022.09~preview1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.16~2022.09~preview1.sh) which already supports Coq version `8.16+rc1` and contains already working (possibly patched / commit pinned) Coq Platform packages.

In case you want to select a different version, please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/274

**Comment by QinshiWang** [comment]
I hope to have [VST zlist](https://github.com/PrincetonUniversity/VST/blob/master/coq-vst-zlist.opam) as an explicitly included package in the next Coq Platform. VST zlist is always included in any VST installation, but having it explicitly mentioned in OPAM will allow packages that depend on VST zlist to recognize that VST zlist is already installed.

**Comment by MSoegtropIMC** [comment]
@QinshiWang : this is definitely possible - can you please create a corresponding issue in the Coq Platform repo?

**Comment by andrew-appel** [comment]
I will leave this issue open for a few days, while I consider whether to create a new release 2.11 of VST that incorporates new concurrency features.   If I don't do anything and if this issue is still open on August 20th, 2022, then someone should close this issue and we will stick with VST 2.10.

**Comment by MSoegtropIMC** [comment]
@andrew-appel : thanks, I can close the issue after August 20th if there is no update.

**Comment by andrew-appel** [comment]
I have created VST release 2.11 and tagged it:
https://github.com/PrincetonUniversity/VST/releases/tag/v2.11

Please use this for the Coq Platform release.

**Comment by MSoegtropIMC** [comment]
Thanks! I updated coq-vst to version 2.11 in the preparation branch and close this issue now.
