### ISSUE TITLE
Misleading error message in forward-call

### ISSUE THREAD

**Issue by lennartberinger** [PrincetonUniversity/VST#64]
Warning_perhaps_funspec_postcondition_needs_EX_outside_PROP_LOCAL_SEP

is occasionally raised even when the postcondition in fact has an outermost EX
(example in hkdf_extract)

**Comment by lennartberinger** [comment]
Indeed it's also raised if the function has a return type but no clause (temp ret_temp ...) in the LOCAL part of POST.

**Comment by andrew-appel** [comment]
This has been fixed, I believe.
The call to give_EX_warning has long been commented out,
and the part regarding the missing (temp ret_temp ...) was fixed more recently.
