### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by matejkosik** [PrincetonUniversity/VST#72]
When I take Coq 8.6 (i.e. branch `v8.6`) and try to compile VST, I get an error message.
```
COQC floyd/library.v
File "./floyd/library.v", line 3, characters 15-34:
Error: Unable to locate library floyd.client_lemmas.
```
Is VST supposed to be compilable with Coq 8.6?

**Comment by lennartberinger** [comment]
The master branch should work for Coq8.6, up to at least make target sha.
Sometimes (and sometimes dependnig on your OS), 'make depend' does 
not identify all dependencies correctly, which may be a reason for your error. 
Could you try to compile the file in question manually:

make floyd/client_lemmas.vo
and then 'make floyd' or 'make' again.

In general it should work if you do the following targets in sequence:

make msl
make veric (*this may trigger making parts of compcert; if you get errors here complaining about 
                     compcert files you may need to go inside the compcert directory and do make 
                     exportclight/Clightdefs.vo, as mentioned in FIRST_README*)
make floyd

You can speed thing up by doing eg "make -kjN msl" to process on N cores, but
again may need to repeat this command 1 or 2 times. 

Let us know if the issue remains.

**Comment by ejgallego** [comment]
Thanks @lennartberinger for the summary, we will try. Do you think a bug in `make depend` should be warranted here?

In general, we think that it would be great if the stability of VST compilation could be improved. It is fairly easy to add a `.travis.yml` file that will allow developers testing their pull requests before merging. Let us know if you need any help for that, the template used in AbsInt/CompCert#161 should basically work here.

As you may be aware, VST is tested as part of the standard Coq Continuous Integration testing; we think this is great as it helps us to introduce unwanted compatibility regressions in Coq and will mean that VST will work out of the box in newer Coq versions.

However, every time the VST builds becomes broken so does our CI infrastructure, and we incur in significant time loss; if these interruptions become too frequent we may have to demote VST to the optional testing suite temporally.

**Comment by mansky1** [comment]
I just fixed (well, deferred really) a bug in make depend, and a fresh clone now builds for me. Please let me know whether it works for you!

**Comment by matejkosik** [comment]
Thanks. That worked!

**Comment by ejgallego** [comment]
@matejkosik can you reopen this ? Does this problem occur in 8.6 too?

@lennartberinger @andrew-appel @scuellar we are afraid that we may have to drop VST from our CI suite soon for the reasons outline in my above message; it seems that the ratio of VST pushes that break our build is too high.

**Comment by lennartberinger** [comment]
We just had some internal discussion and understand your concerns. We're looking into how to to set up travis so that you should see far fewer (well, none we hope) incorrect builds. There seem to be 3 options:
a) have travis operate on our master branch, but have a much stricter internal policy about who pushes to master b) if travis permits this, we could have travis/CI work on a "stable" branch into which we occasionally merge our master but whenever we do so we take care that things don't break. c) like b, but have different branches (mini-releases) each time we commit, and presumably update the travis script each time to only check the most recent one, If option b)  is technically possible it's probably easier to enforce internally than a) and hence preferred - do you have any recommendation?

**Comment by ejgallego** [comment]
Hi @lennartberinger thanks for having a look into this.

I think that if you would like to use travis then it would make sense to submit pulls as Pull Requests as this is the main use case Travis designers had in mind. This way, you push to a branch and once the change has been tested you can merge to `master`. Both b) and c) are IMHO variations of this approach, the point is you only merge to `master` once Travis has passed.

Note that you can indeed merge to `master` with `--fast-forward` so no history noise is created by the pull requests if you would like to avoid that.

Of course, a) is also possible, but our experience has shown that automated testing works better, as humans tend to have subtle variations in the environment that makes manual policies less effective.

Lets us know if you need any help in preparing a `.travis.yml` file.

**Comment by matejkosik** [comment]
@ejgallego @maximedenes It might be worthwhile to explain why we are motivated to deal with `HEAD` rather then picking any known good version, forking that and pushing necessary commits to our fork rather than to upstream.

The benefit for us: we can test Coq with the real stuff rather than with some stale fork.

The benefit for you is that you might get some pull-request for free (related to changes done on Coq trunk).

Of course, this model is meaningful only when:
- we don't push commits to Coq trunk that break it
- you don't push commits to VST that break it (with Coq trunk).

The breakage should be a transitional state caused by delay between:
- us creating the pull-request reflecting the (backward incompatible) changes made in Coq trunk
- you merging the pull-request (after it is deemed acceptable).

WDYT?

**Comment by lennartberinger** [comment]
William and I think this should be ok - we'll consult with Andrew hopefully 
early next week.
