### ISSUE TITLE
Please create a tag for Coq 8.18 in Coq Platform 2023.10

### ISSUE THREAD

**Issue by rtetley** [PrincetonUniversity/VST#727]
The Coq team released Coq `8.18.0` on September 7th, 2023.
The corresponding Coq Platform release `2023.10` should be released before **November 30th, 2023**.
It can be delayed in case of difficulties until January 15th, 2023, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (2.12) **does not work** with Coq `8.18.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit cd6f85a813069ab7742d3f6e1510960230a86e2e on repository https://github.com/PrincetonUniversity/VST - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.18, **preferably before October 31st, 2023**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before October 31st, 2023, it will be included in an early Coq Platform beta release of the for Coq 8.18.0.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.18+beta1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.18+beta1.sh) which already supports Coq version `8.18.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/372

**Comment by andrew-appel** [comment]
I have created the tag  v2.13  for this release.

**Comment by palmskog** [comment]
@rtetley @MSoegtropIMC there are now the following CI-validated packages in the Coq opam archive: `coq-vst.2.13` and `coq-vst-32.2.13` (and their dependencies, including `coq-compcert.3.13.1` and `coq-compcert-32.3.13.1` respectively).

VST v2.13 is incompatible with CompCert 3.13 due to the latter having an incorrect `VERSION` file, this was apparently fixed in 3.13.1.

**Comment by andrew-appel** [comment]
Now that the PR to opam-coq-archive is created, CI'd, and merged, is it time to close this issue?

**Comment by palmskog** [comment]
I think we are still waiting for this part:
> We will close the issue after updating Coq Platform.

**Comment by MSoegtropIMC** [comment]
I updated Coq platform to VST 2.13 (in a branch will be merged today), so I am closing this issue.
