### ISSUE TITLE
mailbox broken: typedef with/without *

### ISSUE THREAD

**Issue by andrew-appel** [PrincetonUniversity/VST#782]
The mailbox example (i.e., "make test4" or "make mailbox") is broken in the master branch, for a long time now, and the only reason we haven't noticed it in the CI is that nobody has rerun clightgen on the .c files, so we have been using very old .v files.

The reason is this:  mailbox/atomic_exchange.h includes concurrency/threads.h.
Some time ago, the typedef for lock_t was changed (in concurrency/threads.h) from `typedef struct ... lock_t;` to `typedef struct ... *lock_t;`.   But nobody updated the C code in mailbox/*.c, so they're all using  `lock_t *p`  et cetera.

Either we should update the C files in mailbox, or mailbox must have its own version of threads.h.

**Comment by andrew-appel** [comment]
In commit 31fcf79 I have worked around this problem by brazenly editing mailbox.v and atomic_exchange.v to keep the old clightgen output, edited for the new AST types.

**Comment by mansky1** [comment]
Okay! I think we should just change the C files in mailbox, and then everything should work.
