### ISSUE TITLE
Request for a -ignore-coq-version option

### ISSUE THREAD

**Issue by Zimmi48** [PrincetonUniversity/VST#79]
As you may already know, VST is part of the external developments that we track in our CI (Travis) for deciding whether a PR can be integrated or not.
For more than a week though, the build of VST has been failing for a completely spurious reason: VST (and CompCert) checks whether the version of Coq is supported but the version of Coq has been increased and thus of course it is not yet supported.
The same problem existed in CompCert and has been fixed by adding the `-ignore-coq-version` option: https://github.com/AbsInt/CompCert/blob/master/configure#L73
So far it was expected that one of the Coq developers would submit a PR here to do the same. But since no one has had time to do it yet, I'm opening this issue in case some VST developer would be kind enough to do it quickly.

**Comment by andrew-appel** [comment]
Done.
.travis.yml now has   IGNORECOQVERSION=true in its make command

**Comment by Zimmi48** [comment]
Thanks!

**Comment by andrew-appel** [comment]
Oops! Previously I had committed that only to the "Andrew" branch.  Now it's merged into the master branch.
