### ISSUE TITLE
Redundent type-checking in sem_shift

### ISSUE THREAD

**Issue by QinxiangCao** [PrincetonUniversity/VST#90]

**Comment by andrew-appel** [comment]
Explanation:  In veric/Cop2.v, 
Definition sem_shift_ii sem_int (sg:signedness) v1 v2 : option val :=
      match v1, v2 with
      | Vint n1, Vint n2 =>
          if Int.ltu n2 Int.iwordsize
          then Some(Vint(sem_int sg n1 n2)) else None
      | _, _ => None
      end.

but if the VeriC type-checker has done its jobs, it should not be necessary to have " if Int.ltu n2 Int.iwordsize then".

**Comment by andrew-appel** [comment]
Fixed.
